# =============================================================================
# batch_runner_studio.py — Streamlit control panel for TSP batch runs
# =============================================================================
# A browser-based replacement for the Tkinter batch_runner_gui_builder.py.
# Reuses the builder as a library (strategy presets, generated-file template)
# so there is exactly one source of truth for what a generated
# batch_runner_gui.py looks like — this app adds what Tk couldn't:
#
#   * Configure   — build an EXPERIMENTS x SEEDS x SCALARS batch from the same
#                   strategy presets, edit reward overrides inline
#   * Generate    — writes <network>/batch_runner_gui.py (same contract as the
#                   Tk builder: run it from Aimsun's Run Script menu)
#   * Run         — instructions for the in-Aimsun run, plus an experimental
#                   headless launcher via aconsole.exe
#   * Monitor     — live tail of batch_results_gui.csv and the newest
#                   controller log while a batch is running
#   * Results     — KPI table, baseline deltas vs NO_TSP, quick charts, and
#                   one-click open of per-run dashboards
#
# Start it with:
#   python -m streamlit run batch_runner_studio.py
# =============================================================================

import ast
import datetime
import glob
import json
import os
import subprocess
import sys
import types

import streamlit as st

try:
    import pandas as pd
except ImportError:
    pd = None

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# ── Import the Tk builder as a library (presets + template). If tkinter is
#    unavailable (headless server), stub it — but never intercept dunders:
#    a module __getattr__ that answers __file__/__path__ with a function
#    poisons inspect.getmodule() for the whole process. ─────────────────────
def _stub_tk_module(name: str) -> types.ModuleType:
    m = types.ModuleType(name)
    def _getattr(attr, _m=name):
        if attr.startswith("__"):
            raise AttributeError(f"stub module {_m} has no attribute {attr}")
        return lambda *a, **kw: None
    m.__getattr__ = _getattr
    return m

try:
    import tkinter  # noqa: F401 — probe only
except ImportError:
    for _tk_name in ("tkinter", "tkinter.ttk", "tkinter.messagebox"):
        sys.modules.setdefault(_tk_name, _stub_tk_module(_tk_name))

sys.path.insert(0, SCRIPT_DIR)
import batch_runner_gui_builder as builder
import beamer_report
# Streamlit's dev server is a long-running process — without this, editing
# batch_runner_gui_builder.py (new presets, template fixes) has no effect
# until the server is manually restarted, because Python only imports a
# module once per process and Streamlit's file-watcher doesn't reliably
# catch changes to modules imported this way. Force a fresh read every
# time this script (re)runs, which Streamlit already does on every
# interaction, so edits to the builder take effect on the very next click.
import importlib as _importlib
builder = _importlib.reload(builder)
beamer_report = _importlib.reload(beamer_report)

AIMSUN_ACONSOLE = r"C:\Program Files\Aimsun\Aimsun Next 26.0.0\aconsole.exe"

KPI_COLUMNS = [
    "stats_AvgBusPassDelay_s",
    "stats_AvgBusTT_s",
    "stats_AvgPassDelay_s",
    "stats_AvgCarPassDelay_s",
    "stats_TotalPassDelay_hrs",
    "stats_TSP_Detections",
    "stats_TSP_Extensions",
    "stats_TSP_Insertions",
    "stats_Net_AvgSpeed_kmh",
    "run_elapsed_s",
]
ID_COLUMNS = ["run_experiment", "run_seed", "run_demand_scalar", "run_success"]

_CONSOLE_WRAPPER = '''# _studio_console_launch.py — GENERATED by batch_runner_studio.py
# Opens the .ang given on the command line in Aimsun console mode, then runs
# this folder's batch_runner_gui.py exactly as Run Script would.
#   aconsole.exe -script _studio_console_launch.py <model.ang>
from PyANGConsole import ANGConsole
import runpy, sys, os

ang = sys.argv[1]
gui = os.path.join(os.path.dirname(os.path.abspath(__file__)), "batch_runner_gui.py")
console = ANGConsole()
if not console.open(ang):
    print("[STUDIO] FATAL: could not open " + ang)
    sys.exit(1)
try:
    runpy.run_path(gui, run_name="__main__")
finally:
    try:
        console.close()
    except Exception:
        pass
'''


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _network_dir(net_key: str) -> str:
    return os.path.join(SCRIPT_DIR, builder.NETWORKS[net_key]["dir_name"])


def _overrides_to_text(ov: dict) -> str:
    return "\n".join(f"{k} = {v!r}" for k, v in ov.items())


def _text_to_overrides(text: str) -> dict:
    out = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise ValueError(f"override line has no '=': {line!r}")
        key, _, val = line.partition("=")
        key = key.strip()
        val = val.strip()
        try:
            out[key] = ast.literal_eval(val)
        except (ValueError, SyntaxError):
            out[key] = val  # keep as raw string (e.g. LSTM_SS)
    return out


def _unique_name(base: str, taken) -> str:
    sanitized_base = builder._sanitize_name(base)
    name, n = sanitized_base, 2
    while name in taken:
        name = f"{sanitized_base}_{n}"
        n += 1
    return name


def _make_experiment(name: str, strategy: str, coordinated: bool,
                     coordination_algo: str, reward_overrides: dict,
                     method_overrides=None, method: str = "",
                     active_intersections=None, enabled: bool = True) -> dict:
    uid = st.session_state._next_uid
    st.session_state._next_uid += 1
    return {
        "name": name, "enabled": enabled,
        "_uid": uid, "method": method,
        "strategy": strategy,
        "coordinated": coordinated,
        "coordination_algo": coordination_algo,
        "active_intersections": active_intersections,
        "reward_overrides": dict(reward_overrides),
        "method_overrides": dict(method_overrides or {}),
    }


def _newest(pattern: str):
    hits = glob.glob(pattern)
    return max(hits, key=os.path.getmtime) if hits else None


def _tail(path: str, n_lines: int = 40) -> str:
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return "".join(f.readlines()[-n_lines:])
    except OSError as e:
        return f"(cannot read {path}: {e})"


def _load_results(csv_path: str):
    if pd is None or not os.path.isfile(csv_path):
        return None
    try:
        return pd.read_csv(csv_path)
    except Exception as e:
        st.error(f"Could not parse {os.path.basename(csv_path)}: {e}")
        return None


# ─────────────────────────────────────────────────────────────────────────────
# Session state
# ─────────────────────────────────────────────────────────────────────────────

if "experiments" not in st.session_state:
    st.session_state.experiments = []          # list of dicts (builder schema)
if "console_proc" not in st.session_state:
    st.session_state.console_proc = None
if "console_log" not in st.session_state:
    st.session_state.console_log = None
if "output_tag" not in st.session_state:
    st.session_state.output_tag = "gui"
if "_next_uid" not in st.session_state:
    st.session_state._next_uid = 0      # unique id counter for experiments

st.set_page_config(page_title="TSP Batch Runner Studio", layout="wide")
st.sidebar.title("TSP Batch Runner Studio")

net_key = st.sidebar.selectbox(
    "Network",
    list(builder.NETWORKS.keys()),
    format_func=lambda k: builder.NETWORKS[k]["label"],
)
NET = builder.NETWORKS[net_key]
NET_DIR = _network_dir(net_key)
GUI_PATH = os.path.join(NET_DIR, "batch_runner_gui.py")
RESULTS_CSV = os.path.join(NET_DIR, f"batch_results_{st.session_state.output_tag}.csv")

page = st.sidebar.radio("Page", ["Configure", "Run", "Monitor", "Results"])
st.sidebar.caption(f"Network folder: `{NET_DIR}`")

output_tag_sidebar = st.sidebar.text_input(
    "Output tag", st.session_state.output_tag,
    help="Output tag affects CSV only: batch_results_{tag}.csv, core_output_{tag}.csv",
    key="output_tag_sidebar")
st.session_state.output_tag = output_tag_sidebar
GUI_PATH = os.path.join(NET_DIR, "batch_runner_gui.py")
RESULTS_CSV = os.path.join(NET_DIR, f"batch_results_{st.session_state.output_tag}.csv")


# ─────────────────────────────────────────────────────────────────────────────
# Page: Configure
# ─────────────────────────────────────────────────────────────────────────────

if page == "Configure":
    st.header("Configure batch")

    col1, col2 = st.columns(2)
    seeds_text = col1.text_input("Seeds (comma-separated)", "300")
    scalars_text = col2.text_input("Demand scalars (comma-separated)", "1.0")

    st.subheader("Experiments")
    presets = NET["presets"]
    pcol1, pcol2 = st.columns([3, 1])
    preset_key = pcol1.selectbox(
        "Strategy preset",
        list(presets.keys()),
        format_func=lambda k: f"{k} — {presets[k]['label']}",
    )
    if pcol2.button("Add experiment", width='stretch'):
        p = presets[preset_key]
        taken = {e["name"] for e in st.session_state.experiments}
        st.session_state.experiments.append(_make_experiment(
            name=_unique_name(preset_key, taken),
            strategy=p["strategy"],
            coordinated=p["coordinated"],
            coordination_algo=p["coordination_algo"],
            reward_overrides=p["reward_overrides"],
            method_overrides=p.get("method_overrides"),
            method=p.get("method", preset_key),
        ))
        st.rerun()

    # ── Paper strategy batch: interactive per-method objective sweep ──────────
    # Step through each paper method (Methods 0–V) and for each one tick which
    # corridor objectives to create focussed variants for. Also include the
    # NoPriority baseline once. Every generated experiment is Pareto-based and
    # Z4-hard-constrained (enforced at generation time and at run time).
    if hasattr(builder, "PAPER_STRATEGY_BATCH") and hasattr(builder, "_OBJECTIVE_TARGET_PRESETS"):
        with st.expander("Paper strategy batch — per-method objective sweep"):
            st.caption(
                "Go through each paper method below. Each method is added once "
                "**as its pure self** (the method-vs-method comparison). Tick "
                "the objective targets you want to sweep for that method — each "
                "tick adds a weight-only variant (method + WOBJ weights) that "
                "does **not** change the method. The NoPriority baseline is "
                "included separately at the top."
            )
            paper_methods = [k for k in builder.PAPER_STRATEGY_BATCH if k != "NO_TSP"]
            target_objectives = ["TARGET_Z1_DELAY", "TARGET_Z2_PROGRESSION",
                                "TARGET_Z3_HEADWAY", "TARGET_Z123_BALANCED"]
            target_labels = {
                "TARGET_Z1_DELAY":         "Z1 delay",
                "TARGET_Z2_PROGRESSION":   "Z2 progression",
                "TARGET_Z3_HEADWAY":       "Z3 headway",
                "TARGET_Z123_BALANCED":    "balanced Z1+Z2+Z3",
            }
            target_icons = {
                "TARGET_Z1_DELAY":         "🔴",
                "TARGET_Z2_PROGRESSION":   "🟢",
                "TARGET_Z3_HEADWAY":       "🔵",
                "TARGET_Z123_BALANCED":    "⚖️",
            }

            for method in paper_methods:
                p = presets.get(method)
                if p is None:
                    continue
                short_label = p["label"].split("—")[-1].strip() if "—" in p["label"] else p["label"]
                cols = st.columns([8, 1, 1, 1, 1])
                cols[0].markdown(f"**{method}**  \n<small>{short_label}</small>",
                                 unsafe_allow_html=True)
                method_targets = {}
                for idx, target in enumerate(target_objectives):
                    with cols[1 + idx]:
                        target_label = f"{target_icons[target]} {target_labels[target]}"
                        method_targets[target] = st.checkbox(
                            target_label, value=True,
                            key=f"paper_{method}_{target}")
                if "paper_method_targets" not in st.session_state:
                    st.session_state.paper_method_targets = {}
                st.session_state.paper_method_targets[method] = method_targets

            include_baseline = st.checkbox(
                "Include NoPriority baseline at the top",
                value=True, key="paper_include_baseline")

            if st.button("Generate paper strategy sweep", type="primary"):
                taken = {e["name"] for e in st.session_state.experiments}
                added = 0

                if include_baseline:
                    bp = presets.get("NO_TSP")
                    if bp is not None:
                        name = _unique_name("NO_TSP", taken)
                        taken.add(name)
                        st.session_state.experiments.append(_make_experiment(
                            name=name,
                            strategy=bp["strategy"],
                            coordinated=bp["coordinated"],
                            coordination_algo=bp["coordination_algo"],
                            reward_overrides=bp["reward_overrides"],
                            method_overrides=bp.get("method_overrides"),
                            method=bp.get("method", "NO_TSP"),
                        ))
                        added += 1

                method_targets_state = st.session_state.get("paper_method_targets", {})
                for method in paper_methods:
                    method_p = presets.get(method)
                    if method_p is None:
                        continue
                    # The pure paper method is always added — this is the
                    # method-vs-method comparison the paper needs.  Objective
                    # ticks below only add WOBJ weight-sweep variants that do
                    # NOT change the method (no ZIG injection).
                    name = _unique_name(method, taken)
                    taken.add(name)
                    st.session_state.experiments.append(_make_experiment(
                        name=name,
                        strategy=method_p["strategy"],
                        coordinated=method_p["coordinated"],
                        coordination_algo=method_p["coordination_algo"],
                        reward_overrides=dict(method_p["reward_overrides"]),
                        method_overrides=dict(method_p.get("method_overrides") or {}),
                        method=method_p.get("method", method),
                    ))
                    added += 1

                    targets = method_targets_state.get(method, {})
                    for target in target_objectives:
                        if not targets.get(target, False):
                            continue
                        # Weight-only variant: pure method + WOBJ weights/scales.
                        # Never merge in the target's method-changing flags
                        # (DCTSP_ZIG_MODE & friends) — those belong to the
                        # WaveGate/ZIG strategy, not to the paper methods.
                        wobj = builder.objective_weight_overrides(target)
                        if not wobj:
                            continue
                        name = _unique_name(f"{method}_{target}", taken)
                        taken.add(name)
                        st.session_state.experiments.append(_make_experiment(
                            name=name,
                            strategy=method_p["strategy"],
                            coordinated=method_p["coordinated"],
                            coordination_algo=method_p["coordination_algo"],
                            reward_overrides=dict(method_p["reward_overrides"]),
                            method_overrides={**dict(method_p.get("method_overrides") or {}),
                                              **wobj},
                            method=method_p.get("method", method),
                        ))
                        added += 1

                st.success(f"Added {added} paper experiment(s).")
                st.rerun()

    # One-click objective-target batch: NO_TSP baseline + one experiment per
    # corridor objective (Z1 delay / Z2 progression / Z3 headway) + balanced
    # reference. Z4 is never offered as a target — it is enforced as a hard
    # feasibility constraint on every generated experiment, no matter what.
    if hasattr(builder, "OBJECTIVE_TARGET_BATCH"):
        with st.expander("Objective-targeted batch — one experiment per target objective"):
            st.caption(
                "Each experiment weights the strategy toward a single corridor "
                "objective (Z1 passenger delay, Z2 progression/bandwidth, Z3 bus "
                "headway). **Z4 (corridor throughput) is not selectable: it is "
                "always applied as a hard constraint** — `Z4_CONSTRAINT_MODE = True` "
                "is force-set on every non-baseline experiment at generation time "
                "and again at run time.")
            target_keys = [k for k in builder.OBJECTIVE_TARGET_BATCH if k in presets]
            chosen_targets = st.multiselect(
                "Experiments to add", target_keys, default=target_keys,
                format_func=lambda k: f"{k} — {presets[k]['label']}",
                key="objective_target_choice")
            if st.button("Add objective-target batch",
                         disabled=not chosen_targets):
                taken = {e["name"] for e in st.session_state.experiments}
                added = 0
                for key in chosen_targets:
                    p = presets[key]
                    name = _unique_name(key, taken)
                    taken.add(name)
                    st.session_state.experiments.append(_make_experiment(
                        name=name,
                        strategy=p["strategy"],
                        coordinated=p["coordinated"],
                        coordination_algo=p["coordination_algo"],
                        reward_overrides=p["reward_overrides"],
                        method_overrides=p.get("method_overrides"),
                        method=p.get("method", key),
                    ))
                    added += 1
                st.success(f"Added {added} objective-target experiment(s).")
                st.rerun()

    # ── TRB Paper full sweep ─────────────────────────────────────────────────
    # One-click: NO_TSP baseline + 5 methods (excluding CENTRALISED) each run
    # PURE, plus a WOBJ weight-sweep variant per objective target (Z1 delay,
    # Z2 progression, Z3 headway, Z123 balanced) that does NOT change the
    # method + seeds 300, 400, 500 + demand scalar 1.0. Covers the paper's
    # full comparison matrix on one network — run it on KG first, then switch
    # to Logan Road and repeat.
    if hasattr(builder, "PAPER_STRATEGY_BATCH") and hasattr(builder, "objective_weight_overrides"):
        with st.expander("TRB Paper — full sweep (5 methods pure + weight sweep × 3 seeds)"):
            st.caption(
                "One-click full experimental plan for the TRB paper on this "
                "network. Creates the NO_TSP baseline plus every paper method "
                "(except CENTRALISED) run **pure** — that is the method-vs-method "
                "comparison — plus one **weight-only variant per objective "
                "target** (Z1/Z2/Z3/balanced WOBJ weights; the method itself is "
                "unchanged, never ZIG-contaminated). "
                "**Before generating, set Seeds to `300, 400, 500` at the top "
                "of this page** for statistical validity. Run on KG first — "
                "then switch networks and click again for Logan Road."
            )
            trb_methods = [k for k in builder.PAPER_STRATEGY_BATCH
                           if k not in ("NO_TSP", "CENTRALISED")]
            trb_targets = ["TARGET_Z1_DELAY", "TARGET_Z2_PROGRESSION",
                           "TARGET_Z3_HEADWAY", "TARGET_Z123_BALANCED"]
            n_combos = 1 + len(trb_methods) + len(trb_methods) * len(trb_targets)
            st.caption(
                f"Adds {n_combos} experiments "
                f"({n_combos} × 3 seeds × 1 scalar = {n_combos * 3} runs) "
                f"for the **{net_key}** network."
            )
            if st.button("Generate TRB full sweep for this network",
                         type="primary"):
                taken = {e["name"] for e in st.session_state.experiments}
                added = 0

                bp = presets.get("NO_TSP")
                if bp is not None:
                    name = _unique_name("NO_TSP", taken)
                    taken.add(name)
                    st.session_state.experiments.append(_make_experiment(
                        name=name,
                        strategy=bp["strategy"],
                        coordinated=bp["coordinated"],
                        coordination_algo=bp["coordination_algo"],
                        reward_overrides=bp["reward_overrides"],
                        method_overrides=bp.get("method_overrides"),
                        method=bp.get("method", "NO_TSP"),
                    ))
                    added += 1

                for method in trb_methods:
                    method_p = presets.get(method)
                    if method_p is None:
                        continue
                    # Pure method — no objective merge, no ZIG injection.
                    name = _unique_name(method, taken)
                    taken.add(name)
                    st.session_state.experiments.append(_make_experiment(
                        name=name,
                        strategy=method_p["strategy"],
                        coordinated=method_p["coordinated"],
                        coordination_algo=method_p["coordination_algo"],
                        reward_overrides=dict(method_p["reward_overrides"]),
                        method_overrides=dict(method_p.get("method_overrides") or {}),
                        method=method_p.get("method", method),
                    ))
                    added += 1
                    # Weight-only objective variants — WOBJ weights/scales only,
                    # never the target's method-changing (ZIG) flags.
                    for target in trb_targets:
                        wobj = builder.objective_weight_overrides(target)
                        if not wobj:
                            continue
                        name = _unique_name(f"{method}_{target}", taken)
                        taken.add(name)
                        st.session_state.experiments.append(_make_experiment(
                            name=name,
                            strategy=method_p["strategy"],
                            coordinated=method_p["coordinated"],
                            coordination_algo=method_p["coordination_algo"],
                            reward_overrides=dict(method_p["reward_overrides"]),
                            method_overrides={**dict(method_p.get("method_overrides") or {}),
                                              **wobj},
                            method=method_p.get("method", method),
                        ))
                        added += 1

                st.success(f"Added {added} experiment(s) for {net_key}.")
                st.rerun()

    # ── CTM strategy × Frequency × Bus Demand sweep ───────────────────────────
    # Cross-joins the cell-transition-model strategies (CellQ-Learn with DP,
    # Nash bargaining / game theory, CTM Q-Learning, exhaustive CTM grid search,
    # Harmony Search with LWR, tabular Q-Learning) with the X1/X2/X3 intervention
    # frequency knob and bus demand multipliers. Each (strategy × frequency ×
    # bus level) combination becomes one experiment, named after its strategy so
    # the method is always visible in the results.
    if hasattr(builder, "SS_BATCH"):
        with st.expander("CTM strategy × Frequency × Bus Demand — cell-transition-model sweep"):
            st.caption(
                "Cross-joins the **cell-transition-model strategies** (CellQ-Learn "
                "with DP, Nash bargaining / game theory, CTM Q-Learning, "
                "exhaustive CTM grid search, Harmony Search with LWR, tabular "
                "Q-Learning) with the intervention-frequency knob X1/X2/X3 (1×/2×/3× "
                "per cycle) and bus demand multipliers. Each experiment names its "
                "strategy so the method is always visible.\n\n"
                "Each strategy keeps its own objective (the shared Pareto "
                "selection layer is weight-free for the paper presets) and that "
                "objective is **identical across X1/X2/X3** — the frequency "
                "override only touches `TSP_CYCLE_LENGTH_OVERRIDE_S` and "
                "`PHASE_SEQ_MAX_PER_CYCLE`, so only the intervention cadence "
                "differs between jobs."
            )

            bus_text = st.text_input(
                "Bus demand scalars (comma-separated)",
                "1.0, 1.5, 2.0, 3.0",
                key="ss_bus_scalars",
                help="1.0 = timetable as modelled; 2.0 = double the buses")

            col_fam, col_freq = st.columns(2)
            with col_fam:
                st.caption("Cell-transition-model strategy")
                ctm_methods = ["CELLQLEARN_DP", "NASHHS", "CELLQLEARN",
                               "CTMGS", "HSLWR", "CPD_QL"]
                ctm_labels = {
                    "CELLQLEARN_DP": "CellQ-Learn with DP (V2X DP)",
                    "NASHHS": "Nash bargaining (game theory)",
                    "CELLQLEARN": "CellQ (CTM Q-Learning)",
                    "CTMGS": "CellSearch (exhaustive grid)",
                    "HSLWR": "WaveGate (Harmony Search + LWR)",
                    "CPD_QL": "CPD-QL (tabular Q-Learning)",
                }
                ctm_sel = {}
                for m in ctm_methods:
                    ctm_sel[m] = st.checkbox(
                        ctm_labels[m], value=True,
                        key=f"ss_strat_{m}",
                        help=f"Cell-transition-model preset key: {m}")
            with col_freq:
                st.caption("Intervention frequency")
                ss_x1 = st.checkbox("X1 — 1 per cycle (135 s window)", value=True, key="ss_x1")
                ss_x2 = st.checkbox("X2 — 2 per cycle (67.5 s window)", value=True, key="ss_x2")
                ss_x3 = st.checkbox("X3 — 3 per cycle (45 s window)", value=True, key="ss_x3")

            include_baseline = st.checkbox(
                "Include NO_TSP baseline at each bus level",
                value=True, key="ss_include_baseline")

            if st.button("Generate CTM strategy × Frequency × Bus Demand sweep", type="primary"):
                try:
                    bus_scalars = builder._parse_num_list(bus_text, float)
                    if not bus_scalars:
                        raise ValueError("bus demand scalars list is empty")
                except ValueError as e:
                    st.error(f"Invalid bus demand scalars: {e}")
                    st.stop()

                taken = {e["name"] for e in st.session_state.experiments}
                added = 0

                sel_ctm = [m for m in ctm_methods if ctm_sel.get(m)]
                freq_keys = [f for f, flag in [("X1", ss_x1), ("X2", ss_x2),
                                               ("X3", ss_x3)] if flag]
                freq_over = getattr(builder, "_SS_FREQ_OVERRIDES", {})
                if not freq_keys:
                    st.error("Select at least one intervention frequency.")
                    st.stop()

                for bus_level in bus_scalars:
                    for method in sel_ctm:
                        p = presets.get(method)
                        if p is None:
                            continue
                        for freq in freq_keys:
                            mo = dict(p.get("method_overrides") or {})
                            fov = freq_over.get(freq) or {}
                            mo.update(fov)
                            name = _unique_name(
                                f"{method}_{freq}_BUSx{bus_level:g}", taken)
                            taken.add(name)
                            st.session_state.experiments.append(_make_experiment(
                                name=name,
                                strategy=p["strategy"],
                                coordinated=p["coordinated"],
                                coordination_algo=p["coordination_algo"],
                                reward_overrides=dict(p.get("reward_overrides") or {}),
                                method_overrides=mo,
                                method=p.get("method", method),
                            ))
                            added += 1

                    if include_baseline:
                        bp = presets.get("NO_TSP")
                        if bp is not None:
                            name = _unique_name(f"NO_TSP_BUSx{bus_level:g}", taken)
                            taken.add(name)
                            st.session_state.experiments.append(_make_experiment(
                                name=name,
                                strategy=bp["strategy"],
                                coordinated=bp["coordinated"],
                                coordination_algo=bp["coordination_algo"],
                                reward_overrides=bp["reward_overrides"],
                                method_overrides=bp.get("method_overrides"),
                                method=bp.get("method", "NO_TSP"),
                            ))
                            added += 1

                st.success(f"Added {added} CTM strategy × Frequency × Bus "
                           f"Demand experiment(s).")
                st.rerun()

            # ── TEST run: one strategy across the frequency sweep focus ──────
            # Clicking this instead of the full sweep adds a minimal batch: the
            # FIRST selected strategy at all three frequencies X1/X2/X3 and a
            # single bus level (1.0), so the only thing changing between jobs is
            # TSP_CYCLE_LENGTH_OVERRIDE_S + PHASE_SEQ_MAX_PER_CYCLE — a quick way
            # to confirm the sweep jobs produce different results.
            tcol_btn, tcol_help = st.columns([1, 3])
            with tcol_btn:
                test_clicked = st.button(
                    "Generate TEST run (one strategy, frequency focus)",
                    key="ss_test_generate",
                    help="Adds TEST_* experiments: one strategy across X1/X2/X3 "
                         "at bus 1.0 only.")
            with tcol_help:
                st.caption(
                    "TEST: one strategy (first selected; default CellQ-Learn "
                    "with DP) across all three frequencies at bus level 1.0 — "
                    "confirms the frequency jobs differ without running the full "
                    "cross-join.")
            if test_clicked:
                sel_ctm = [m for m in ctm_methods if ctm_sel.get(m)]
                test_method = sel_ctm[0] if sel_ctm else "CELLQLEARN_DP"
                freq_over = getattr(builder, "_SS_FREQ_OVERRIDES", {})
                taken = {e["name"] for e in st.session_state.experiments}
                added = 0
                p = presets.get(test_method)
                if p is not None:
                    for freq in ("X1", "X2", "X3"):
                        mo = dict(p.get("method_overrides") or {})
                        mo.update(freq_over.get(freq) or {})
                        name = _unique_name(f"TEST_{test_method}_{freq}", taken)
                        taken.add(name)
                        st.session_state.experiments.append(_make_experiment(
                            name=name,
                            strategy=p["strategy"],
                            coordinated=p["coordinated"],
                            coordination_algo=p["coordination_algo"],
                            reward_overrides=dict(p.get("reward_overrides") or {}),
                            method_overrides=mo,
                            method=p.get("method", test_method),
                        ))
                        added += 1
                if include_baseline:
                    bp = presets.get("NO_TSP")
                    if bp is not None:
                        name = _unique_name("TEST_NO_TSP", taken)
                        taken.add(name)
                        st.session_state.experiments.append(_make_experiment(
                            name=name,
                            strategy=bp["strategy"],
                            coordinated=bp["coordinated"],
                            coordination_algo=bp["coordination_algo"],
                            reward_overrides=bp["reward_overrides"],
                            method_overrides=bp.get("method_overrides"),
                            method=bp.get("method", "NO_TSP"),
                        ))
                        added += 1
                st.success(
                    f"Added {added} TEST experiment(s): one strategy "
                    f"({test_method}) across X1/X2/X3 at bus 1.0. "
                    f"Click **Generate batch_runner_gui.py** to write the files.")
                st.rerun()

    # ── Agency-preference × demand sensitivity sweep (TRB methods) ────────────
    # The TRB paper's five strategies (CPD-QL, CellQ, CellSearch, WaveGate,
    # NashGate) + CellQ-Learn with DP (V2X DP), each crossed with three
    # "what-the-agency-cares-about" regimes and the demand scalars set at the
    # top of this page. The regime dials:
    #   * Bus-vs-car passenger value  — BUS_OCC_OVERRIDE / CAR_OCC_OVERRIDE
    #     (the alpha/beta analog in the shared Pareto selection layer)
    #   * Bus lateness                — META_LATENESS_TAKEOVER_S × META_HW_SENSITIVITY
    #     plus WOBJ_GAMMA (Z3 weight) for the weighted-objective trace
    #   * Congestion / demand         — DEMAND_SCALARS (top of page)
    # Generates (strategies × regimes + baseline) experiments; the Beamer deck
    # for the run is auto-generated on completion (Monitor) and via the
    # Results page.
    if hasattr(builder, "PAPER_STRATEGY_BATCH"):
        with st.expander("Agency preference × demand sensitivity — TRB methods"):
            st.caption(
                "Crosses the TRB paper's five strategies **CPD-QL, CellQ, "
                "CellSearch, WaveGate, NashGate** plus **CellQ-Learn with DP "
                "(V2X DP)** with three agency-preference regimes and the "
                "demand scalars set at the top of this page.\n\n"
                "**Regime dials (per strategy, uniform):**\n"
                "- Bus-vs-car passenger value → `BUS_OCC_OVERRIDE` / "
                "`CAR_OCC_OVERRIDE` (the bus-vs-car valuation in the shared "
                "Pareto selection layer — the weight-free α/β analog)\n"
                "- Bus lateness → `META_LATENESS_TAKEOVER_S` × "
                "`META_HW_SENSITIVITY` + `WOBJ_GAMMA`\n"
                "- Congestion / demand uncertainty → `DEMAND_SCALARS` "
                "(e.g. `0.7, 1.0, 1.5`), crossed over all experiments\n\n"
                "On **Generate**, the Beamer deck auto-generates when the "
                "batch completes (Monitor page) and can be rebuilt/compiled "
                "from the **Results** page."
            )

            pol_methods = ["CPD_QL", "CELLQLEARN", "CTMGS", "HSLWR",
                           "NASHHS", "CELLQLEARN_DP"]
            pol_labels = {
                "CPD_QL": "CPD-QL (Tabular Q-Learning)",
                "CELLQLEARN": "CellQ (CTM Q-Learning)",
                "CTMGS": "CellSearch (Exhaustive grid)",
                "HSLWR": "WaveGate (Harmony Search)",
                "NASHHS": "NashGate (Nash bargaining)",
                "CELLQLEARN_DP": "CellQ-Learn with DP (V2X DP)",
            }
            pol_sel = {}
            pol_grid = st.columns(6)
            for i, m in enumerate(pol_methods):
                with pol_grid[i % 6]:
                    pol_sel[m] = st.checkbox(
                        pol_labels[m], value=True,
                        key=f"pol_strat_{m}",
                        help=f"TRB method preset key: {m}")

            pol_include_base = st.checkbox(
                "Include NO_TSP baseline", value=True, key="pol_include_base")

            st.markdown("**Regime dials** (edit each `bus_occ, car_occ, "
                        "takeover_s, hw_sens, wobj_gamma`):")
            rc1, rc2, rc3 = st.columns(3)
            regime_inputs = {
                "PRO_BUS": rc1.text_input(
                    "PRO_BUS (bus-first)", "60.0, 1.2, 30.0, 2.5, 0.5",
                    key="pol_regime_PRO_BUS"),
                "BALANCED": rc2.text_input(
                    "BALANCED (default)", "40.0, 1.5, 60.0, 1.5, 0.2",
                    key="pol_regime_BALANCED"),
                "PRO_CAR": rc3.text_input(
                    "PRO_CAR (car-first)", "30.0, 2.5, 9999.0, 0.5, 0.0",
                    key="pol_regime_PRO_CAR"),
            }

            _sel_methods = [m for m in pol_methods if pol_sel.get(m)]
            try:
                _seeds_n = len(builder._parse_num_list(seeds_text, int))
                _scalars_n = len(builder._parse_num_list(scalars_text, float))
            except ValueError:
                _seeds_n = _scalars_n = 0
            _n_pol = (len(_sel_methods) * 3 + (3 if pol_include_base else 0))
            st.caption(
                f"Adds **{_n_pol} experiments** "
                f"({len(_sel_methods)} strategies × 3 regimes"
                f"{' + 3 per-regime NO_TSP baselines' if pol_include_base else ''}) × "
                f"{_seeds_n} seed(s) × {_scalars_n} scalar(s) = "
                f"**{_n_pol * _seeds_n * _scalars_n} runs** for {net_key}. "
                f"Set Seeds (e.g. `300, 400, 500`) and Demand scalars "
                f"(e.g. `0.7, 1.0, 1.5`) above first.")

            if st.button("Generate agency-preference batch", type="primary"):
                regimes_parsed = {}
                for reg, text in regime_inputs.items():
                    try:
                        vals = builder._parse_num_list(text, float)
                        if len(vals) != 5:
                            raise ValueError(f"expected 5 values, got {len(vals)}")
                        regimes_parsed[reg] = {
                            "BUS_OCC_OVERRIDE": vals[0],
                            "CAR_OCC_OVERRIDE": vals[1],
                            "META_LATENESS_TAKEOVER_S": vals[2],
                            "META_HW_SENSITIVITY": vals[3],
                            "WOBJ_GAMMA": vals[4],
                        }
                    except ValueError as e:
                        st.error(f"Invalid regime {reg}: {e} — "
                                 "need `bus_occ, car_occ, takeover_s, hw_sens, "
                                 "wobj_gamma`.")
                        st.stop()

                taken = {e["name"] for e in st.session_state.experiments}
                added = 0

                for method in _sel_methods:
                    p = presets.get(method)
                    if p is None:
                        continue
                    for reg, reg_ov in regimes_parsed.items():
                        mo = dict(p.get("method_overrides") or {})
                        mo.update(reg_ov)
                        name = _unique_name(f"{method}_{reg}", taken)
                        taken.add(name)
                        st.session_state.experiments.append(_make_experiment(
                            name=name,
                            strategy=p["strategy"],
                            coordinated=p["coordinated"],
                            coordination_algo=p["coordination_algo"],
                            reward_overrides=dict(p.get("reward_overrides") or {}),
                            method_overrides=mo,
                            method=p.get("method", method),
                        ))
                        added += 1

                if pol_include_base:
                    bp = presets.get("NO_TSP")
                    if bp is not None:
                        # One NO_TSP baseline per regime so the passenger-weighted
                        # total-delay KPI is computed with the SAME bus/car occupancy
                        # assumptions as the matching TSP experiment.  Previously a
                        # single bare NO_TSP sat at junction-default occupancy, so
                        # every delta-vs-baseline for PRO_BUS/BALANCED/PRO_CAR was
                        # apples-vs-oranges.
                        for reg, reg_ov in regimes_parsed.items():
                            _mo = dict(bp.get("method_overrides") or {})
                            _mo["BUS_OCC_OVERRIDE"] = reg_ov["BUS_OCC_OVERRIDE"]
                            _mo["CAR_OCC_OVERRIDE"] = reg_ov["CAR_OCC_OVERRIDE"]
                            name = _unique_name(f"NO_TSP_{reg}", taken)
                            taken.add(name)
                            st.session_state.experiments.append(_make_experiment(
                                name=name,
                                strategy=bp["strategy"],
                                coordinated=bp["coordinated"],
                                coordination_algo=bp["coordination_algo"],
                                reward_overrides=dict(bp.get("reward_overrides") or {}),
                                method_overrides=_mo,
                                method=bp.get("method", "NO_TSP"),
                            ))
                            added += 1

                st.success(
                    f"Added {added} agency-preference experiment(s) for "
                    f"{len(_sel_methods)} strategies × 3 regimes"
                    f"+ {len(regimes_parsed) if pol_include_base else 0} per-regime "
                    f"NO_TSP baseline(s). "
                    f"Now set Seeds / Demand scalars above and click "
                    f"**Generate batch_runner_gui.py**.")
                st.rerun()

    with st.expander("Sensitivity sweep — generate one experiment per parameter value"):
        st.caption(
            "Pick the preset selected above as the base config, choose a parameter, "
            "and give a list of values. One experiment per value is added, each "
            "identical to the base preset except for that single override — the "
            "same pattern as the ZIG_SWEEP / WOBJ_SWEEP blocks in batch_runner.py, "
            "but built from the UI instead of hand-edited experiment lists.")
        base_p = presets[preset_key]
        override_keys = [k for k in base_p["reward_overrides"].keys()
                          if isinstance(base_p["reward_overrides"][k], (int, float))
                          and not isinstance(base_p["reward_overrides"][k], bool)]
        scol1, scol2, scol3 = st.columns([2, 2, 1])
        if override_keys:
            param_choice = scol1.selectbox(
                "Parameter", override_keys + ["(custom name)"], key="sweep_param_choice")
        else:
            param_choice = "(custom name)"
            scol1.info("This preset has no numeric overrides to pick from — use a custom name.")
        if param_choice == "(custom name)":
            sweep_param = scol1.text_input(
                "Custom parameter name", key="sweep_param_custom",
                placeholder="e.g. ZIG_BALANCE_FACTOR")
        else:
            sweep_param = param_choice
        sweep_values_text = scol2.text_input(
            "Values (comma-separated)", "0.5, 1.0, 1.5, 2.0", key="sweep_values")
        if scol3.button("Add sweep", width='stretch', disabled=not sweep_param):
            try:
                raw_values = [v.strip() for v in sweep_values_text.split(",") if v.strip()]
                if not raw_values:
                    raise ValueError("values list is empty")
                parsed_values = []
                for v in raw_values:
                    try:
                        parsed_values.append(ast.literal_eval(v))
                    except (ValueError, SyntaxError):
                        parsed_values.append(v)
                taken = {e["name"] for e in st.session_state.experiments}
                added = 0
                for v in parsed_values:
                    ov = dict(base_p["reward_overrides"])
                    ov[sweep_param] = v
                    v_tag = str(v).replace(".", "p").replace("-", "m")
                    name = _unique_name(
                        builder._sanitize_name(f"{preset_key}_{sweep_param}_{v_tag}"), taken)
                    taken.add(name)
                    st.session_state.experiments.append(_make_experiment(
                        name=name,
                        strategy=base_p["strategy"],
                        coordinated=base_p["coordinated"],
                        coordination_algo=base_p["coordination_algo"],
                        reward_overrides=ov,
                        method_overrides=base_p.get("method_overrides"),
                        method=base_p.get("method", preset_key),
                    ))
                    added += 1
                st.success(f"Added {added} sweep experiment(s) over {sweep_param} = {parsed_values}.")
                st.rerun()
            except Exception as e:
                st.error(f"Could not build sweep: {e}")

    with st.expander("CellQ-Learn DP Z123 Balanced — Full Sensitivity Sweep"):
        st.caption(
            "One-click full sensitivity grid for CELLQLEARN_DP_TARGET_Z123_BALANCED. "
            "Cross-joins three axes: **bus occupancy (pax/bus)**, **cycle projection "
            "(REWARD_FUTURE_HORIZON_CYCLES)**, and **detection update interval "
            "(CELLQLEARN_DP_DT_S)**. NO_TSP baselines at each bus occupancy level "
            "are included for delta comparison at each occupancy assumption."
        )
        n_dp = 3 * 3 * 3  # bus(20,40,60) x cyc(1,2,3) x dt(1,3,5) = 27
        n_baselines = 3     # NO_TSP at each bus occupancy
        n_total = n_dp + n_baselines
        st.caption(
            f"Adds **{n_total} experiments** "
            f"({n_dp} CELLQLEARN_DP + {n_baselines} NO_TSP baselines). "
            f"Set **Seeds** (e.g. `300, 400, 500`) above before generating."
        )

        if st.button("Generate CellQ-Learn DP Sensitivity Sweep", type="primary"):
            cellq_method = presets.get("CELLQLEARN_DP")
            obj_target   = builder._OBJECTIVE_TARGET_PRESETS.get("TARGET_Z123_BALANCED")
            no_tsp_p     = presets.get("NO_TSP")

            if cellq_method is None or obj_target is None:
                st.error("Required presets not found — make sure CELLQLEARN_DP "
                         "and TARGET_Z123_BALANCED are available for this network.")
                st.stop()

            taken = {e["name"] for e in st.session_state.experiments}
            added = 0

            base_method = dict(cellq_method.get("method_overrides") or {})
            base_method.update(dict(obj_target.get("method_overrides") or {}))
            base_reward = dict(cellq_method.get("reward_overrides") or {})
            base_reward.update(dict(obj_target.get("reward_overrides") or {}))

            bus_levels = [20, 40, 60]
            cyc_levels = [1, 2, 3]
            dt_levels  = [1, 3, 5]

            if no_tsp_p is not None:
                for bus in bus_levels:
                    name = _unique_name(f"NO_TSP_BUS{bus}", taken)
                    taken.add(name)
                    st.session_state.experiments.append(_make_experiment(
                        name=name,
                        strategy=no_tsp_p["strategy"],
                        coordinated=no_tsp_p["coordinated"],
                        coordination_algo=no_tsp_p["coordination_algo"],
                        reward_overrides={"BUS_OCC_OVERRIDE": float(bus)},
                        method_overrides={},
                        method=no_tsp_p.get("method", "NO_TSP"),
                    ))
                    added += 1

            for bus in bus_levels:
                for cyc in cyc_levels:
                    for dt in dt_levels:
                        name = _unique_name(
                            f"CELLQLEARN_DP_Z123_BUS{bus}_CYC{cyc}_DT{dt}", taken)
                        taken.add(name)

                        mo = dict(base_method)
                        mo["BUS_OCC_OVERRIDE"] = float(bus)
                        mo["CELLQLEARN_DP_DT_S"] = float(dt)
                        mo["REWARD_FUTURE_HORIZON_CYCLES"] = float(cyc)

                        ro = dict(base_reward)
                        ro["REWARD_FUTURE_HORIZON_CYCLES"] = float(cyc)

                        st.session_state.experiments.append(_make_experiment(
                            name=name,
                            strategy=cellq_method["strategy"],
                            coordinated=cellq_method["coordinated"],
                            coordination_algo=cellq_method["coordination_algo"],
                            reward_overrides=ro,
                            method_overrides=mo,
                            method=cellq_method.get("method", "CELLQLEARN_DP"),
                        ))
                        added += 1

            st.success(f"Added {added} sensitivity experiment(s). "
                       f"Now set Seeds to `300, 400, 500` above and click Generate.")
            st.rerun()

    if not st.session_state.experiments:
        st.info("No experiments yet — pick a preset above and click **Add experiment**.")

    deleted_uid = st.session_state.get("_delete_experiment", None)
    if deleted_uid is not None:
        st.session_state.experiments = [
            e for e in st.session_state.experiments
            if e["_uid"] != deleted_uid
        ]
        st.session_state["_delete_experiment"] = None
        st.rerun()

    for i, exp in enumerate(st.session_state.experiments):
        uid = exp["_uid"]
        row_cols = st.columns([6, 1])
        with row_cols[0]:
            with st.expander(f"{i + 1}. {exp['name']}  ({exp['strategy']})", expanded=False):
                c1, c2, c3, c4 = st.columns([3, 1, 2, 1])
                exp["name"] = builder._sanitize_name(
                    c1.text_input("Name", exp["name"], key=f"name_{uid}"))
                exp["enabled"] = c2.checkbox("Enabled", exp["enabled"], key=f"en_{uid}")
                exp["coordination_algo"] = c3.selectbox(
                    "Coordination algo", ["KALMAN", "SHOCKWAVE", "OBJECTIVE", "ADAPTIVE"],
                    index=["KALMAN", "SHOCKWAVE", "OBJECTIVE", "ADAPTIVE"].index(
                        exp["coordination_algo"]),
                    key=f"algo_{uid}")
                exp["coordinated"] = c4.checkbox("Coordinated", exp["coordinated"], key=f"coord_{uid}")

                ov_text = st.text_area(
                    "Reward overrides (one `KEY = value` per line)",
                    _overrides_to_text(exp["reward_overrides"]),
                    height=160, key=f"ov_{uid}")
                try:
                    exp["reward_overrides"] = _text_to_overrides(ov_text)
                except ValueError as e:
                    st.error(str(e))
        with row_cols[1]:
            if st.button("Delete", key=f"del_{exp['_uid']}",
                         help=f"Remove {exp['name']}"):
                st.session_state["_delete_experiment"] = exp["_uid"]
                st.rerun()

    st.divider()
    st.caption(
        "Z4 hard-constraint policy: on Generate, every non-baseline experiment "
        "gets `Z4_CONSTRAINT_MODE = True` (and a default `Z4_TOLERANCE_VEH_S = 90.0` "
        "if unset) — even if the overrides above say otherwise.")

    gui_label = "Generate batch_runner_gui.py"
    if st.button(gui_label, type="primary",
                 disabled=not st.session_state.experiments):
        try:
            seeds = builder._parse_num_list(seeds_text, int)
            scalars = builder._parse_num_list(scalars_text, float)
            if not seeds or not scalars:
                raise ValueError("seeds and scalars must each have at least one value")
            if not os.path.isfile(os.path.join(NET_DIR, "batch_runner.py")):
                raise FileNotFoundError(f"{NET_DIR} has no batch_runner.py to build on")
            content = builder.render_batch_runner_gui(
                st.session_state.experiments, seeds, scalars,
                output_tag=st.session_state.output_tag)
            with open(GUI_PATH, "w", encoding="utf-8") as f:
                f.write(content)
            n = len([e for e in st.session_state.experiments if e["enabled"]])
            n_total = n * len(seeds) * len(scalars)
            try:
                meta = {
                    "tag": st.session_state.output_tag,
                    "n_experiments": n,
                    "n_seeds": len(seeds),
                    "n_scalars": len(scalars),
                    "expected_total": n_total,
                    "generated_at": datetime.datetime.now().isoformat(timespec="seconds"),
                }
                with open(os.path.join(NET_DIR, "_studio_batch_meta.json"),
                          "w", encoding="utf-8") as f:
                    json.dump(meta, f, indent=2)
            except Exception as e:
                st.warning(f"Could not persist batch metadata: {e}")
            st.success(
                f"Written `{GUI_PATH}` — {n} experiment(s) × {len(seeds)} seed(s) × "
                f"{len(scalars)} scalar(s) = **{n_total} runs**. "
                f"Now run it from Aimsun (see the **Run** page).")
            with st.expander("Preview generated file"):
                st.code(content, language="python")
        except Exception as e:
            st.error(f"Generation failed: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# Page: Run
# ─────────────────────────────────────────────────────────────────────────────

elif page == "Run":
    st.header("Run the batch")

    if os.path.isfile(GUI_PATH):
        st.success(f"Generated script found: `{GUI_PATH}` "
                   f"(modified {datetime.datetime.fromtimestamp(os.path.getmtime(GUI_PATH)):%Y-%m-%d %H:%M:%S})")
    else:
        st.warning("No generated batch_runner_gui.py yet — build one on the Configure page.")

    st.subheader("Option A — inside Aimsun (recommended)")
    st.markdown(
        f"""
1. Open the **{NET['label']}** model (`.ang`) in Aimsun Next.
2. Menu **Tools → Run Script** (or the Python console) and pick
   `{GUI_PATH}`.
3. Watch progress on the **Monitor** page here — it tails the results CSV and
   the controller log as runs complete.
        """)

    st.subheader("Option B — headless via aconsole (experimental)")
    st.caption(
        "Launches Aimsun's console runner as a subprocess — no Aimsun window. "
        "This actually executes the whole batch, so only press Launch when you "
        "mean it. Untested path: verify the first run's output before relying on it.")
    if not os.path.isfile(AIMSUN_ACONSOLE):
        st.info(f"aconsole.exe not found at `{AIMSUN_ACONSOLE}` — Option B unavailable.")
    else:
        angs = sorted(glob.glob(os.path.join(NET_DIR, "*.ang")))
        if not angs:
            st.info(f"No .ang model files found in {NET_DIR}.")
        else:
            ang = st.selectbox("Model file", angs, format_func=os.path.basename)
            proc = st.session_state.console_proc
            running = proc is not None and proc.poll() is None
            c1, c2 = st.columns(2)
            if c1.button("Launch headless batch", type="primary",
                         disabled=running or not os.path.isfile(GUI_PATH)):
                wrapper = os.path.join(NET_DIR, "_studio_console_launch.py")
                with open(wrapper, "w", encoding="utf-8") as f:
                    f.write(_CONSOLE_WRAPPER)
                logs_dir = os.path.join(NET_DIR, "logs")
                os.makedirs(logs_dir, exist_ok=True)
                log_path = os.path.join(
                    logs_dir,
                    f"studio_console_{datetime.datetime.now():%Y%m%d_%H%M%S}.log")
                log_f = open(log_path, "w", encoding="utf-8")
                st.session_state.console_proc = subprocess.Popen(
                    [AIMSUN_ACONSOLE, "-script", wrapper, ang],
                    cwd=NET_DIR, stdout=log_f, stderr=subprocess.STDOUT)
                st.session_state.console_log = log_path
                st.rerun()
            if c2.button("Stop", disabled=not running):
                proc.terminate()
                st.rerun()
            if running:
                st.info(f"Console batch running (pid {proc.pid}) — "
                        f"log: `{st.session_state.console_log}`. See **Monitor**.")
            elif proc is not None:
                st.info(f"Last console batch exited with code {proc.poll()} — "
                        f"log: `{st.session_state.console_log}`")


# ─────────────────────────────────────────────────────────────────────────────
# Page: Monitor
# ─────────────────────────────────────────────────────────────────────────────

elif page == "Monitor":
    st.header("Monitor")

    def _render_monitor():
        df = _load_results(RESULTS_CSV)
        c1, c2, c3 = st.columns(3)
        if df is not None:
            c1.metric("Runs completed", len(df))
            ok = int(df["run_success"].astype(str).str.lower().eq("true").sum()) \
                if "run_success" in df.columns else len(df)
            c2.metric("Successful", ok)
            if "run_elapsed_s" in df.columns and len(df):
                c3.metric("Avg run time", f"{df['run_elapsed_s'].astype(float).mean():.0f}s")
            show_cols = [c for c in ID_COLUMNS + KPI_COLUMNS if c in df.columns]
            st.dataframe(df[show_cols].tail(15), width='stretch')
        else:
            st.info(f"No results yet at `{RESULTS_CSV}`.")

        # ── Auto-generate the Beamer deck when the current batch completes ────
        _meta_path = os.path.join(NET_DIR, "_studio_batch_meta.json")
        _deck_tex = os.path.join(
            NET_DIR, "beamer_report",
            f"{st.session_state.output_tag}_policy_sweep.tex")
        try:
            with open(_meta_path, "r", encoding="utf-8") as f:
                _meta = json.load(f)
            _expected = int(_meta.get("expected_total", 0))
        except (OSError, ValueError, TypeError):
            _meta = None
            _expected = 0

        if df is not None and _expected > 0:
            _ok_count = int(df["run_success"].astype(str).str.lower()
                            .eq("true").sum()) if "run_success" in df.columns else len(df)
            if len(df) >= _expected and _ok_count >= _expected:
                _stale = not os.path.isfile(_deck_tex) or (
                    os.path.getmtime(_deck_tex) < os.path.getmtime(RESULTS_CSV))
                if _stale:
                    try:
                        os.makedirs(os.path.dirname(_deck_tex), exist_ok=True)
                        beamer_report.render_deck(
                            RESULTS_CSV, _deck_tex,
                            title=f"{NET['label']} — agency preference × demand sensitivity",
                            subtitle=f"TRB methods · batch_results_{st.session_state.output_tag}.csv")
                        st.success(
                            f"Batch complete — Beamer deck auto-generated at "
                            f"`{_deck_tex}` (compile from the **Results** page).")
                    except Exception as e:
                        st.warning(f"Could not auto-generate Beamer deck: {e}")

        if st.session_state.console_log and os.path.isfile(st.session_state.console_log):
            st.subheader("Console launcher log")
            st.code(_tail(st.session_state.console_log, 30), language="text")

        newest_log = _newest(os.path.join(NET_DIR, "logs", "Aimsun_TSP_Log_*.txt"))
        if newest_log:
            st.subheader(f"Controller log — {os.path.basename(newest_log)}")
            st.code(_tail(newest_log, 40), language="text")

    # Auto-refresh when the running Streamlit supports fragments; else a button.
    if hasattr(st, "fragment"):
        st.caption("Auto-refreshing every 10 s.")
        st.fragment(run_every=10)(_render_monitor)()
    else:
        if st.button("Refresh"):
            st.rerun()
        _render_monitor()


# ─────────────────────────────────────────────────────────────────────────────
# Page: Results
# ─────────────────────────────────────────────────────────────────────────────

elif page == "Results":
    st.header("Results")
    if pd is None:
        st.error("pandas is required for this page: python -m pip install pandas")
        st.stop()

    results_tag = st.session_state.get("output_tag", "gui")
    sources = {
        f"GUI batch (batch_results_{results_tag}.csv)": RESULTS_CSV,
        "Main batch (batch_results.csv)": os.path.join(NET_DIR, "batch_results.csv"),
    }
    src_label = st.selectbox("Results file", list(sources.keys()))
    df = _load_results(sources[src_label])
    if df is None:
        st.info(f"`{sources[src_label]}` not found or unreadable.")
        st.stop()

    kpis = st.multiselect(
        "KPI columns",
        [c for c in df.columns if c.startswith(("stats_", "aimsun_", "wobj_", "run_elapsed"))],
        default=[c for c in KPI_COLUMNS if c in df.columns],
    )
    id_cols = [c for c in ID_COLUMNS if c in df.columns]
    st.dataframe(df[id_cols + kpis], width='stretch')

    # ── Baseline deltas ──────────────────────────────────────────────────────
    if "run_experiment" in df.columns and kpis:
        st.subheader("Delta vs baseline")
        d = df.copy()
        demand_vals = sorted(d["run_demand_scalar"].dropna().unique().tolist()) \
            if "run_demand_scalar" in d.columns else []
        seed_vals = sorted(d["run_seed"].dropna().unique().tolist()) \
            if "run_seed" in d.columns else []
        f1, f2, f3 = st.columns(3)
        sel_demands = (f1.multiselect("Demand scalars (compare at same value)",
                                      demand_vals, default=demand_vals)
                       if demand_vals else [])
        sel_seeds = (f2.multiselect("Seeds", seed_vals, default=seed_vals)
                     if seed_vals else [])
        sel_regimes = f3.multiselect(
            "Regime / bus value (name filter)",
            ["PRO_BUS", "BALANCED", "PRO_CAR", "NO_TSP"],
            default=["PRO_BUS", "BALANCED", "PRO_CAR", "NO_TSP"],
            help="Filters experiments by a token in the experiment name — "
                 "e.g. pick PRO_BUS to compare strategies at the same bus value.")

        if sel_demands:
            d = d[d["run_demand_scalar"].isin(sel_demands)]
        if sel_seeds:
            d = d[d["run_seed"].isin(sel_seeds)]
        if sel_regimes:
            d = d[d["run_experiment"].astype(str).apply(
                lambda n: any(r in n.upper() for r in sel_regimes))]
        if d.empty:
            st.info("No runs match the current filters.")
        else:
            experiments = sorted(d["run_experiment"].astype(str).unique())
            default_base = next(
                (e for e in experiments if "NO_TSP" in e.upper()),
                experiments[0])
            baseline = st.selectbox("Baseline experiment", experiments,
                                    index=experiments.index(default_base))
            kpi = st.selectbox("KPI", kpis)
            show_per_seed = st.checkbox(
                "Show per-seed rows (don't average seeds)", value=False)
            try:
                keys = [k for k in ("run_seed", "run_demand_scalar") if k in d.columns]
                base = (d[d["run_experiment"].astype(str) == baseline]
                        .groupby(keys)[kpi].mean().rename("baseline"))
                merged = d.join(base, on=keys)
                merged["delta"] = merged[kpi].astype(float) - merged["baseline"].astype(float)
                group_cols = ["run_experiment"]
                if "run_demand_scalar" in merged.columns:
                    group_cols.append("run_demand_scalar")
                if show_per_seed and "run_seed" in merged.columns:
                    group_cols.append("run_seed")
                summary = (merged.groupby(group_cols)
                           .agg(mean_value=(kpi, "mean"), mean_delta=("delta", "mean"),
                                n_runs=(kpi, "size"))
                           .round(2))
                st.dataframe(summary, width='stretch')
                chart = summary["mean_delta"].copy()
                if isinstance(chart.index, pd.MultiIndex):
                    chart = chart[chart.index.get_level_values(0) != baseline]
                else:
                    chart = chart.drop(labels=[baseline], errors="ignore")
                st.bar_chart(chart)
            except Exception as e:
                st.warning(f"Could not compute deltas for {kpi}: {e}")

    # ── Beamer deck ──────────────────────────────────────────────────────────
    st.subheader("Beamer deck")
    deck_dir = os.path.join(NET_DIR, "beamer_report")
    deck_tex = os.path.join(deck_dir,
                            f"{st.session_state.output_tag}_policy_sweep.tex")
    deck_c1, deck_c2 = st.columns(2)
    if deck_c1.button("Generate Beamer deck"):
        try:
            os.makedirs(deck_dir, exist_ok=True)
            beamer_report.render_deck(
                sources[src_label], deck_tex,
                title=f"{NET['label']} — agency preference × demand sensitivity",
                subtitle=f"TRB methods · {os.path.basename(sources[src_label])}")
            st.success(f"Wrote `{deck_tex}`. "
                       "Compile with the button below, or manually with "
                       "`pdflatex -interaction=nonstopmode <file>.tex`.")
        except Exception as e:
            st.error(f"Could not generate deck: {e}")
    if deck_c2.button("Compile deck (pdflatex)"):
        if not os.path.isfile(deck_tex):
            st.warning("Generate the deck first.")
        else:
            ok, msg = beamer_report.compile_deck(deck_tex)
            if ok:
                st.success(msg)
            else:
                st.warning(msg)

    # ── Per-run artefacts ────────────────────────────────────────────────────
    st.subheader("Open run artefacts")
    res_root = os.path.join(NET_DIR, "results")
    run_dirs = sorted(glob.glob(os.path.join(res_root, "*")),
                      key=os.path.getmtime, reverse=True)
    if run_dirs:
        run_dir = st.selectbox("Run folder (newest first)", run_dirs,
                               format_func=os.path.basename)
        c1, c2 = st.columns(2)
        if c1.button("Open folder in Explorer"):
            os.startfile(run_dir)  # noqa: S606 — local desktop convenience
        dash = os.path.join(run_dir, "tsp_dashboard.html")
        if c2.button("Open tsp_dashboard.html", disabled=not os.path.isfile(dash)):
            os.startfile(dash)  # noqa: S606
    else:
        st.info(f"No run folders under `{res_root}` yet.")
