# _studio_console_launch.py — GENERATED by batch_runner_studio.py
# Opens the .ang given on the command line in Aimsun console mode, then runs
# this folder's batch_runner_gui.py exactly as Run Script would.
#   aconsole.exe -script _studio_console_launch.py <model.ang>
from PyANGConsole import ANGConsole
import runpy, sys, os

ang = sys.argv[1]
gui = os.path.join(os.path.dirname(os.path.abspath(__file__)), "batch_runner_gui.py")
console = ANGConsole()
if not console.open(ang):
    print("[STUDIO] FATAL: could not open " + ang)
    sys.exit(1)
try:
    runpy.run_path(gui, run_name="__main__")
finally:
    try:
        console.close()
    except Exception:
        pass
