# =============================================================================
# batch_runner_quicktest.py — GENERATED by batch_runner_gui_builder.py on 2026-08-20 13:55:59
# =============================================================================
# Do not hand-edit the EXPERIMENTS / SEEDS / DEMAND_SCALARS block below —
# re-run batch_runner_gui_builder.py and Generate again instead, so this file
# stays reproducible from the GUI settings that produced it.
#
# Run from Aimsun's "Run Script" menu (or the Python console inside Aimsun),
# same as batch_runner.py / batch_runner_wavegate.py in this folder.
# =============================================================================

import os as _os
import sys as _sys
import time as _time
import importlib.util as _ilu
from PyANGKernel import GKSystem

# __file__ is not defined when Aimsun exec's the script in headless/batch
# mode, so fall back to the active model's project directory.
try:
    _SCRIPT_DIR = _os.path.dirname(_os.path.abspath(__file__))
except NameError:
    _model = GKSystem.getSystem().getActiveModel()
    _SCRIPT_DIR = _model.getDocumentDirectory().absolutePath()

if _SCRIPT_DIR not in _sys.path:
    _sys.path.insert(0, _SCRIPT_DIR)

# ── Shared infrastructure — imported from this folder's batch_runner.py ──────
_br_path = _os.path.join(_SCRIPT_DIR, "batch_runner.py")
_spec = _ilu.spec_from_file_location("_br_gui", _br_path)
_br = _ilu.module_from_spec(_spec)
_sys.modules["_br_gui"] = _br
try:
    _spec.loader.exec_module(_br)
except SystemExit:
    pass

log = _br.log
set_control_mode = _br.set_control_mode
set_coordinated = _br.set_coordinated
set_coordination_algo = _br.set_coordination_algo
set_seed = _br.set_seed
set_reward_weights = _br.set_reward_weights
write_run_config = _br.write_run_config
collect_run_metrics = _br.collect_run_metrics
append_master_csv = _br.append_master_csv
write_core_output = _br.write_core_output
get_first_replication = _br.get_first_replication
run_replication = _br.run_replication
_purge_pyc = _br._purge_pyc
set_demand_scalar = _br.set_demand_scalar
_set_logging = _br._set_logging

CONTROLLER_PATH = _br.CONTROLLER_PATH
RUN_CONFIG_PATH = _br.RUN_CONFIG_PATH
PROJECT_DIR = _br.PROJECT_DIR

BATCH_RESULTS_CSV = _os.path.join(_SCRIPT_DIR, "batch_results_quicktest.csv")
CORE_OUTPUT_PATH = _os.path.join(_SCRIPT_DIR, "core_output_quicktest.csv")

# =============================================================================
# ── GUI-configured run definition ─────────────────────────────────────────────
# =============================================================================
# TRAIN on new seeds (600-1100), EVALUATE on 300/400/500 whose NO_TSP baseline
# is already cached (no_tsp_baseline.csv) -- so this batch runs ZERO NO_TSP.
# Train seeds MUST come before eval seeds (the Q-table trains then freezes).
# Keep this list in sync with BXT_TRAIN_SEEDS / BXT_EVAL_SEEDS in
# kg/intersection_controller.py.
SEEDS = [300]   # SMOKE-TEST single seed (was [300,400,500] multi-seed) — expand to [300,400,500] after smoke passes
DEMAND_SCALARS = [1.0]

EXPERIMENTS = [
    {
        "name": 'NO_TSP',
        "enabled": False,   # baseline is cached in no_tsp_baseline.csv -- NO_TSP is
                            # deterministic per seed (verified identical across 10+
                            # batches), so re-running it is pure waste.
        "strategy": 'NORMAL',
        "method": 'NO_TSP',
        "coordinated": False,
        "coordination_algo": 'KALMAN',
        "active_intersections": None,
        "reward_overrides": {},
        "method_overrides": {},
    },
    {
        "name": 'CELLQLEARN',
        "enabled": True,
        "strategy": 'GLOBAL_REWARD',
        "method": 'CELLQLEARN',
        "coordinated": True,
        "coordination_algo": 'SHOCKWAVE',
        "active_intersections": None,
        "reward_overrides": {
            'GLOBAL_REWARD_MODE': True,
            'PARETO_SELECTION_MODE': False,
            'Z4_CONSTRAINT_MODE': True,
            'Z4_TOLERANCE_VEH_S': 90.0,
            'REWARD_FUTURE_HORIZON_CYCLES': 1.0,
            'REWARD_FUTURE_DEBT_GAIN': 0.35,
            'REWARD_FUTURE_OFFSET_GAIN': 0.2,
        },
        "method_overrides": {
            'BXT_MODE': True,
            'BXT_DT_S': 1.0,
            'BXT_EPSILON': 0.02,
            'BXT_ALPHA': 0.2,   # raised 0.05->0.2: cold-start Q needs fast convergence
            'BXT_GAMMA': 0.01,
            'BXT_CAR_OCC': 1.2,
            'BXT_BALANCE_FACTOR': 1.1,
            'TSP_CYCLE_LENGTH_OVERRIDE_S': 135.0,
            'PHASE_SEQ_MAX_PER_CYCLE': 1,
            # ── Analytic cost veto (the +4.5% mechanism, §35) ──
            'DECIDER_COST_VETO_RATIO': 1.0,
            # ── Option 1: warm-start per-signal Q from a cross-signal pool (§40) ──
            'BXT_SHARE_Q_ACROSS_SIGNALS': False,   # full sharing gridlocked (§39)
            'BXT_WARMSTART_FROM_SHARED': True,
            # ── Verify harmony/shockwave predictions ──
            'BXT_DELAY_DIAG': True,
        },
    },
    # ── Comparators: other paper strategies (each disables the other modes so
    #    a previous experiment's mode cannot leak through the module cache) ──
    {
        "name": 'DCTSP_ZIG',                 # HSLWR harmony-search / shockwave green-band — TUNED v2 (was catastrophic 1192h)
        "enabled": True,
        "strategy": 'GLOBAL_REWARD',
        "method": 'DCTSP_ZIG',
        "coordinated": True,
        "coordination_algo": 'SHOCKWAVE',
        "active_intersections": None,
        "reward_overrides": {
            'GLOBAL_REWARD_MODE': True,
            'DCTSP_ZIG_MODE': True,
            'MP_ECTM_MODE': False, 'BXT_MODE': False, 'BARGAIN_SPM_MODE': False,
            'ZIG_BALANCE_FACTOR': 0.55,              # was 1.0 — stricter INS gate (was permissive)
            'ZIG_GE_BALANCE_FACTOR': 1.0,            # was 2.0 default — tighten GE too
            'ZIG_PHASE_OVERLAP_S': 3.0,              # was 0.5 — restore 13s eff_delay gate
            'ZIG_MIN_GAIN_S': 8.0,                   # new — veto marginal INS
            'ZIG_ENABLE_SEQ': False,                 # was True — disable ER/PT churn (590/ run)
            'ZIG_ENABLE_GR': False,                  # disable green-realloc candidates
            'DCTSP_MIN_INS_DURATION_S': 12.0,        # was 10 — shorten disruptive set
            'DCTSP_MAX_INS_DURATION_S': 20.0,        # was 25
            'DCTSP_CONGESTION_GATE': True,           # was missing — block when density>0.65
            'DCTSP_CONGESTION_GATE_FRACTION': 0.65,
            'NETWORK_FACTOR': 1.0,
            'NETWORK_FACTOR_DENSITY_RAMP': True,     # was False — scale cost with density
            'REWARD_SIDE_SECTION_WEIGHT': 1.0,       # was missing — count all side streets
        },
        "method_overrides": {},
    },
    {
        "name": 'DCTSP_MP_ECTM',             # CTMGS: MP + enhanced-CTM green-split (Bao 2026) — TUNED v2 (was 0/0 flatlined)
        "enabled": True,
        "strategy": 'GLOBAL_REWARD',
        "method": 'DCTSP_MP_ECTM',
        "coordinated": True,
        "coordination_algo": 'KALMAN',
        "active_intersections": None,
        "reward_overrides": {
            'GLOBAL_REWARD_MODE': True,
            'MP_ECTM_MODE': True,
            'DCTSP_ZIG_MODE': False, 'BXT_MODE': False, 'BARGAIN_SPM_MODE': False,
            'MP_ECTM_DT_S': 1.0,
            'MP_ECTM_MIN_EXT_S': 5.0,               # was 3.0 — avoid 3s phantom INS
            'MP_ECTM_MAX_EXT_S': 15.0,              # was 8.0 — allow meaningful GE
            'MP_ECTM_CAR_OCC': 1.2,                 # was 1.6 — match BXT 1.2 (fixes 16x queue weighting)
            'MP_ECTM_BALANCE_FACTOR': 1.15,          # was 0.75 — was vetoing everything
            'MP_ECTM_GE_BALANCE_FACTOR': 1.4,        # was 2.0 default — tighten GE slightly
            'SELFORG_MIN_BUS_DELAY_S': 6.0,          # was 10.0 default — lower bus delay gate
            'ZIG_PHASE_OVERLAP_S': 2.0,              # was default 3.0 — eff 8s gate not 13s
            'DCTSP_CONGESTION_GATE': False,          # disable — was blocking CTM
            'REWARD_SIDE_SECTION_WEIGHT': 1.0,
        },
        "method_overrides": {},
    },
    {
        "name": 'DCTSP_BARGAIN_SPM',         # Nash-bargaining (game-theoretic) cooperative SPM — TUNED v2 (was +0.5%)
        "enabled": True,
        "strategy": 'GLOBAL_REWARD',
        "method": 'DCTSP_BARGAIN_SPM',
        "coordinated": True,
        "coordination_algo": 'SHOCKWAVE',
        "active_intersections": None,
        "reward_overrides": {
            'GLOBAL_REWARD_MODE': True,
            'BARGAIN_SPM_MODE': True,
            'DCTSP_ZIG_MODE': False, 'MP_ECTM_MODE': False, 'BXT_MODE': False,
            'DCTSP_GREEN_REALLOC_MODE': True,
            'GREEN_REALLOC_RECOVER_FRACTION': 1.0,
            'BG_DET_LVL_IMM_S': 4.0, 'BG_DET_LVL_NEAR_S': 12.0, 'BG_DET_LVL_FAR_S': 24.0,
            'BG_BUS_W_IMM': 1.6, 'BG_BUS_W_NEAR': 1.35, 'BG_BUS_W_FAR': 1.10, 'BG_BUS_W_VFAR': 0.95,
            'BG_SPM_RISK_WEIGHT': 1.0,               # was 1.8 — was doubling side cost
            'BG_EQ_FAIRNESS_WEIGHT': 0.55,
            'BG_MIN_BUS_DELAY_S': 4.0,               # was 5.0 — slightly more permissive
            'BG_MIN_GAIN_S': 3.0,                    # was 5.0 — 200pax ->120pax gate
            'BG_CASCADE_MULT': 1.25,                 # was 2.0 — was doubling cascade
            'BG_MB_WEIGHT': 0.30,
            'DCTSP_CONGESTION_GATE': True,
            'DCTSP_CONGESTION_GATE_FRACTION': 0.85,  # was 0.75 — less blocking
            'REWARD_SIDE_SECTION_WEIGHT': 1.0,       # was 0.5 — count all side streets
            'WOBJ_ALPHA': 0.7,                       # new — rebalance Z1 vs Z2
            'WOBJ_BETA': 0.3,
        },
        "method_overrides": {},
    },
]

if __name__ == "__main__":
    try:
        _rt_proj = _br.get_project_dir()
        CONTROLLER_PATH = _os.path.join(_rt_proj, "intersection_controller.py")
        RUN_CONFIG_PATH = _os.path.join(_rt_proj, "run_config.py")
        PROJECT_DIR = _rt_proj
        _br.CONTROLLER_PATH = CONTROLLER_PATH
        _br.RUN_CONFIG_PATH = RUN_CONFIG_PATH
        _br.PROJECT_DIR = PROJECT_DIR
    except Exception as _e:
        print(f"[GUI] WARNING: could not resolve project dir from model: {_e} — using script dir")

    enabled = [e for e in EXPERIMENTS if e.get("enabled", True)]
    n_total = len(enabled) * len(SEEDS) * len(DEMAND_SCALARS)

    # Start every run of this generated script with a clean results file.
    # The results CSV and core output are append-only across
    # invocations, so without this, rows from long-past experiment lists
    # (renamed/deleted/failed experiments from a previous Generate) linger
    # forever and end up mixed into the dashboard alongside this run's data.
    # Archived (renamed), never deleted -- old rows stay recoverable on disk.
    _archive_ts = _time.strftime("%Y%m%d_%H%M%S")
    for _stale in (BATCH_RESULTS_CSV, CORE_OUTPUT_PATH):
        try:
            if _os.path.isfile(_stale):
                _base, _ext = _os.path.splitext(_stale)
                _archived = f"{_base}_archive_{_archive_ts}{_ext}"
                _os.rename(_stale, _archived)
                print(f"[GUI] Archived previous results -> {_os.path.basename(_archived)}")
        except Exception as _e:
            print(f"[GUI] WARNING: could not archive {_stale}: {_e}")

    # ── Seed the fresh results CSV with the CACHED NO_TSP baseline ────────────
    # NO_TSP is deterministic per seed, so instead of re-running it we inject the
    # cached rows (no_tsp_baseline.csv) for the seeds this batch evaluates.  The
    # dashboard then compares CELLQLEARN against NO_TSP with zero NO_TSP runs.
    try:
        import csv as _csv
        _baseline_path = _os.path.join(_SCRIPT_DIR, "no_tsp_baseline.csv")
        if _os.path.isfile(_baseline_path):
            with open(_baseline_path, newline="") as _bf:
                _brows = [r for r in _csv.DictReader(_bf)
                          if int(float(r.get("run_seed", -1))) in set(SEEDS)]
            if _brows:
                _hdr = list(_brows[0].keys())
                with open(BATCH_RESULTS_CSV, "w", newline="") as _of:
                    _w = _csv.DictWriter(_of, fieldnames=_hdr)
                    _w.writeheader()
                    for _r in _brows:
                        _w.writerow(_r)
                print(f"[GUI] Injected {len(_brows)} cached NO_TSP baseline row(s) "
                      f"for seeds {sorted({int(float(r['run_seed'])) for r in _brows})} "
                      f"-> no NO_TSP runs needed")
        else:
            print("[GUI] NOTE: no_tsp_baseline.csv not found -- run NO_TSP once to create it")
    except Exception as _e:
        print(f"[GUI] WARNING: NO_TSP baseline injection failed: {_e}")

    log("=" * 68)
    log("BATCH_RUNNER_quicktest — generated from batch_runner_gui_builder.py")
    log(f"  {len(enabled)} experiment(s)  x  {len(SEEDS)} seed(s)  x  {len(DEMAND_SCALARS)} scalar(s)  =  {n_total} runs")
    for i, e in enumerate(enabled, 1):
        log(f"  [{i}/{len(enabled)}] {e['name']}  method={e.get('method', '-')}  strategy={e['strategy']}  coordinated={e['coordinated']}")
    log(f"  Results -> {BATCH_RESULTS_CSV}")
    log("=" * 68)

    rep = get_first_replication()
    run_num = 0
    failures = []
    base_demands = {}

    # ── Auto-calibrated objective scales — measured from the first successful
    # baseline (NO_TSP) seed so each normalised Z* starts at ~1.0 regardless of
    # network, demand, or simulation duration. Once calibrated, all subsequent
    # non-baseline experiments use these values instead of hardcoded defaults.
    _baseline_scales = None

    # Silence VERBOSE/LOG_*/heartbeat/status-dashboard console spam for the
    # duration of the batch, same as batch_runner.py's full sweep does.
    # Restored in `finally` below so interactive use afterward is normal again.
    try:
        _set_logging(CONTROLLER_PATH, enabled=False)
    except Exception as e:
        log(f"WARNING: could not disable controller logging: {e}")

    try:
        for scalar in DEMAND_SCALARS:
            try:
                set_demand_scalar(scalar, base_demands)
            except Exception as e:
                log(f"WARNING: demand scalar {scalar}: {e}")

            for exp in enabled:
                exp_name = exp["name"]
                strategy = exp["strategy"]
                coordinated = exp.get("coordinated", False)
                coord_algo = exp.get("coordination_algo", "KALMAN")
                reward_overrides = exp.get("reward_overrides", {}) or {}
                method_overrides = exp.get("method_overrides", {}) or {}
                reward_overrides = dict(reward_overrides)
                reward_overrides.update(method_overrides)
                is_baseline = (strategy == "NORMAL")
                # Z4 hard-constraint policy: re-asserted at run time so even a
                # hand-edited EXPERIMENTS block cannot disable the throughput gate.
                if not is_baseline:
                    reward_overrides["Z4_CONSTRAINT_MODE"] = True
                    reward_overrides.setdefault("Z4_TOLERANCE_VEH_S", 300.0)
                    # Auto-calibrated objective scales from the baseline run so
                    # alpha/beta/gamma weights are directly interpretable:
                    #   Z*_normalised = Z*_raw_per_hour / Z*_SCALE  ≈  1.0 at baseline
                    if _baseline_scales is not None:
                        for _sk, _sv in _baseline_scales.items():
                            reward_overrides.setdefault(_sk, _sv)
                bus_predictor = str(reward_overrides.get("BUS_PREDICTOR_TYPE", "ADAPTIVE_KALMAN")).upper()

                try:
                    set_control_mode(strategy, CONTROLLER_PATH, exp.get("active_intersections"))
                except Exception as e:
                    print(f"[GUI] FATAL: cannot patch strategy for {exp_name}: {e}")
                    for seed in SEEDS:
                        failures.append({"experiment": exp_name, "seed": seed, "error": str(e)})
                    continue

                try:
                    set_coordinated(CONTROLLER_PATH, coordinated)
                    set_coordination_algo(CONTROLLER_PATH, coord_algo)
                except Exception as e:
                    print(f"[GUI] WARNING: coord patch for {exp_name}: {e}")

                _global_reward = bool(reward_overrides.get("GLOBAL_REWARD_MODE", False))
                _numeric_ov = {k: v for k, v in reward_overrides.items() if k != "GLOBAL_REWARD_MODE"}
                _run_cfg = None if (is_baseline and not _numeric_ov) else (_numeric_ov or None)

                if not is_baseline:
                    try:
                        set_reward_weights(CONTROLLER_PATH, _numeric_ov or None)
                    except Exception as e:
                        log(f"WARNING: reward patch: {e}")

                for seed in SEEDS:
                    run_num += 1
                    print("-" * 68)
                    print(f"[GUI] Run {run_num}/{n_total} | {exp_name} | seed={seed} | scalar={scalar}")

                    set_seed(rep, seed)
                    write_run_config(exp_name, strategy, seed, scalar,
                                     coordinated, coord_algo, RUN_CONFIG_PATH,
                                     global_reward_mode=_global_reward,
                                     reward_cfg=_run_cfg,
                                     bus_predictor=bus_predictor,
                                     results_csv_name=_os.path.basename(BATCH_RESULTS_CSV))
                    _purge_pyc(CONTROLLER_PATH)

                    t0 = _time.time()
                    success = True
                    try:
                        run_replication(rep)
                    except Exception as e:
                        success = False
                        failures.append({"experiment": exp_name, "seed": seed, "error": str(e)})
                        print(f"[GUI]   EXCEPTION during simulation: {e}")

                    elapsed = _time.time() - t0
                    print(f"[GUI]   elapsed={elapsed:.0f}s  success={success}")
                    try:
                        metrics = collect_run_metrics(
                            PROJECT_DIR, strategy, seed, scalar,
                            exp_name, coordinated, elapsed, success,
                            bus_predictor=bus_predictor)
                        append_master_csv(BATCH_RESULTS_CSV, metrics)
                        write_core_output(CORE_OUTPUT_PATH, metrics, reward_overrides)
                        # Auto-calibrate objective scales from the first
                        # successful baseline seed so normalised Z* values
                        # start at ~1.0 regardless of network or demand.
                        if is_baseline and _baseline_scales is None and success:
                            _sim_h = max(float(metrics.get("stats_SimDuration_hrs", 1.0) or 1.0), 0.1)
                            _z1 = max(float(metrics.get("wobj_Z1_total", 1) or 1), 1.0) / _sim_h
                            _z2 = max(float(metrics.get("wobj_Z2_total", 1) or 1), 1.0) / _sim_h
                            _z3 = max(float(metrics.get("wobj_Z3_total", 1) or 1), 1.0) / _sim_h
                            _baseline_scales = {
                                "WOBJ_Z1_SCALE": round(_z1, 0),
                                "WOBJ_Z2_SCALE": round(_z2, 0),
                                "WOBJ_Z3_SCALE": round(_z3, 0),
                            }
                            print(f"[GUI]   auto-calibrated objective scales: "
                                  f"Z1={_z1:.0f} Z2={_z2:.0f} Z3={_z3:.0f} "
                                  f"(per sim-hour from {exp_name} seed={seed})")
                        print(f"[GUI]   written -> {_os.path.basename(BATCH_RESULTS_CSV)}")
                    except Exception as e:
                        print(f"[GUI]   ERROR collecting metrics: {e}")
                        failures.append({"experiment": exp_name, "seed": seed, "error": str(e)})
    finally:
        # Restore logging regardless of success/failure, same as batch_runner.py.
        try:
            _set_logging(CONTROLLER_PATH, enabled=True)
            log("Controller logging restored to True.")
        except Exception as e:
            log(f"WARNING: could not re-enable controller logging: {e}")

    print("=" * 68)
    print(f"[GUI] Batch complete: {run_num} runs, {len(failures)} failures")
    for f in failures:
        print(f"[GUI]   FAILED: {f}")
    print(f"[GUI] Results CSV : {BATCH_RESULTS_CSV}")

    # Regenerate the dashboard from the now-COMPLETE results file. AAPIFinish
    # (in shared_tsp_engine/engine.py) already regenerates it after every
    # individual replication, but that happens before this script appends
    # that replication's own row to BATCH_RESULTS_CSV (append_master_csv runs
    # AFTER run_replication() returns here) -- so each in-flight dashboard is
    # always missing the run that just finished. Rebuilding once more here,
    # after every row is in, guarantees the final dashboard is complete.
    try:
        import importlib
        import generate_dashboard as _gd
        importlib.reload(_gd)
        _suffix = "_" + _os.path.splitext(_os.path.basename(BATCH_RESULTS_CSV))[0].removeprefix("batch_results").lstrip("_") \
                  if _os.path.basename(BATCH_RESULTS_CSV) != "batch_results.csv" else ""
        _gd.generate(
            batch_csv=BATCH_RESULTS_CSV if _os.path.isfile(BATCH_RESULTS_CSV) else None,
            out_html=_os.path.join(_SCRIPT_DIR, f"tsp_dashboard{_suffix}.html"),
            log_dir=_os.path.join(_SCRIPT_DIR, "logs"),
        )
        print(f"[GUI] Final dashboard written -> tsp_dashboard{_suffix}.html")
    except Exception as e:
        print(f"[GUI] WARNING: final dashboard regeneration failed: {e}")

    # ── Beamer deck (policy sweeps only) ─────────────────────────────────────
    # On completion, write the Beamer deck for agency-preference x demand
    # sensitivity batches (experiment names like HSLWR_PRO_BUS). The .tex is
    # always written; it also compiles to PDF when pdflatex is available.
    try:
        import re as _re
        _pol_re = _re.compile(
            r"^(CPD_QL|CELLQLEARN_DP|CELLQLEARN|CTMGS|HSLWR|NASHHS)_(PRO_BUS|PRO_CAR|BALANCED)$")
        _pol_enabled = [e for e in enabled if _pol_re.match(str(e.get("name", "")))]
        if _pol_enabled:
            _deck_dir = _os.path.join(_SCRIPT_DIR, "beamer_report")
            _os.makedirs(_deck_dir, exist_ok=True)
            _bname = _os.path.basename(BATCH_RESULTS_CSV)
            _tag = _bname[len("batch_results_"):-4] if _bname.startswith("batch_results_") else "gui"
            _deck_tex = _os.path.join(_deck_dir, _tag + "_policy_sweep.tex")
            _root = _SCRIPT_DIR
            if not _os.path.isfile(_os.path.join(_root, "beamer_report.py")):
                _root = _os.path.dirname(_SCRIPT_DIR)
            if _root not in _sys.path:
                _sys.path.insert(0, _root)
            try:
                import beamer_report as _beamer
                _beamer.render_deck(
                    BATCH_RESULTS_CSV, _deck_tex,
                    title=_os.path.basename(_SCRIPT_DIR) + " - agency-preference x demand sensitivity",
                    subtitle=_bname)
                print("[GUI] Beamer deck written -> %s" % _deck_tex)
                _ok, _msg = _beamer.compile_deck(_deck_tex)
                print("[GUI] Beamer compile: %s" % _msg)
            except Exception as _e:
                print("[GUI] WARNING: beamer deck generation failed: %s" % _e)
    except Exception as _e:
        print("[GUI] WARNING: beamer deck step failed: %s" % _e)
