# =============================================================================
# plot_queue_monitor.py — Queue length monitoring dashboard
#
# Creates time-series plots of queue lengths at all intersections at 60-second
# intervals, allowing verification of strategy performance and delay calculations.
#
# Run from any Python environment with matplotlib + pandas:
#   python plot_queue_monitor.py
#
# Or from the Aimsun Scripting menu (no AAPI required).
# =============================================================================

import os
import sys
import json
import glob

from datetime import datetime

# Add Aimsun packages path before importing matplotlib
_AIMSUN_PACKAGES = r"C:\AimsunPackages"
if os.path.isdir(_AIMSUN_PACKAGES) and _AIMSUN_PACKAGES not in sys.path:
    sys.path.insert(0, _AIMSUN_PACKAGES)

# Inject the shared project venv so pandas/plotly/etc. are importable when this
# script is called from inside Aimsun (which uses a minimal Python environment).
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
for _vsp in [
    os.path.join(_THIS_DIR, '..', 'logan_road_new', '.venv', 'Lib', 'site-packages'),
    os.path.join(_THIS_DIR, '.venv', 'Lib', 'site-packages'),
]:
    _vsp = os.path.normpath(_vsp)
    if os.path.isdir(_vsp) and _vsp not in sys.path:
        sys.path.insert(1, _vsp)
        break
del _THIS_DIR, _vsp
sys.path.insert(0, r"C:\AimsunPackages")
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.gridspec import GridSpec
import pandas as pd
import numpy as np

# =============================================================================
# ── CONFIGURATION ─────────────────────────────────────────────────────────────
# =============================================================================
RESULTS_ROOT   = r"D:\Aimsun_Results"  # Change to your results directory
PLOTS_OUT      = os.path.join(RESULTS_ROOT, "queue_monitor")
INTERVAL_S     = 60  # Snapshot interval in seconds
SIMULATION_DURATION_S = 3600  # Default simulation duration (1 hour)

# Intersection IDs from the corridor (update if needed)
INTERSECTION_IDS = [
    17249, 17308, 17383, 17498, 17628, 17963, 18044, 18942,  # Logan North
    19196, 19363, 19474, 19882, 21895  # Logan South
]

# Strategy colors (same as plot_results.py for consistency)
STRATEGY_COLOURS = {
    "NORMAL":               "#FF9800",
    "URTSP":                "#4CAF50",
    "HARMONY":              "#2196F3",
    "DYNAOPAC":             "#E91E63",
    "DYNAOPAC_COORD":       "#E91E63",
    "DYNAOPAC_INDEP":       "#9C27B0",
    "GROUP_BASED":          "#9C27B0",
    "GROUP_BASED_URTSP":    "#673AB7",
    "GROUP_BASED_HARMONY":  "#3F51B5",
}
DEFAULT_COLOUR = "#9E9E9E"

# =============================================================================
# ── DATA LOADING ──────────────────────────────────────────────────────────────
# =============================================================================

def _parse_folder(folder_name):
    """Extract strategy and seed from folder names."""
    parts = folder_name.split('_')
    for i, p in enumerate(parts):
        if p.lower().startswith('seed') and len(p) > 4:
            try:
                seed     = int(p[4:])
                strategy = '_'.join(parts[:i])
                return strategy, seed
            except ValueError:
                pass
    return None, None


def load_section_counts(results_root):
    """
    Load section_counts_*.csv files from each run folder.
    These files contain cumulative vehicle counts at detectors,
    which we can use to estimate queue lengths.
    """
    all_data = []
    
    for folder in os.listdir(results_root):
        fp = os.path.join(results_root, folder)
        if not os.path.isdir(fp):
            continue
            
        strategy, seed = _parse_folder(folder)
        if strategy is None:
            continue
            
        # Look for section counts files (generated by Simulation_Stats.py)
        section_files = glob.glob(os.path.join(fp, "section_counts_*.csv"))
        if not section_files:
            continue
            
        for sf in section_files:
            try:
                df = pd.read_csv(sf)
                # Add metadata
                df['_strategy'] = strategy
                df['_seed'] = seed
                df['_folder'] = folder
                all_data.append(df)
            except Exception as e:
                print(f"[QUEUE] WARNING: {sf}: {e}")
    
    return pd.concat(all_data, ignore_index=True) if all_data else pd.DataFrame()


def load_replication_timeseries(results_root):
    """
    Load replication timeseries data if available.
    This provides second-by-second statistics.
    """
    all_data = []
    
    for folder in os.listdir(results_root):
        fp = os.path.join(results_root, folder)
        if not os.path.isdir(fp):
            continue
            
        strategy, seed = _parse_folder(folder)
        if strategy is None:
            continue
            
        # Look for timeseries files
        ts_files = glob.glob(os.path.join(fp, "*timeseries*.csv"))
        for tsf in ts_files:
            try:
                df = pd.read_csv(tsf)
                df['_strategy'] = strategy
                df['_seed'] = seed
                all_data.append(df)
            except Exception as e:
                pass
    
    return pd.concat(all_data, ignore_index=True) if all_data else pd.DataFrame()


def estimate_queue_from_detectors(section_df):
    """
    Estimate queue length from detector data.
    Queue = upstream count - downstream count (for each section).
    
    This assumes detectors at entry and exit of each link.
    """
    if section_df.empty:
        return pd.DataFrame()
    
    # Group by time and intersection
    queue_data = []
    
    # Required columns: time, section_id, upstream_count, downstream_count
    required_cols = ['time', 'section_id', 'upstream_count', 'downstream_count']
    if not all(col in section_df.columns for col in required_cols):
        print("[QUEUE] Missing required columns in section data")
        print(f"  Available: {list(section_df.columns)}")
        return pd.DataFrame()
    
    for (time, section_id), group in section_df.groupby(['time', 'section_id']):
        upstream = group['upstream_count'].sum()
        downstream = group['downstream_count'].sum()
        queue = max(0, upstream - downstream)
        queue_data.append({
            'time': time,
            'section_id': section_id,
            'queue_length': queue
        })
    
    return pd.DataFrame(queue_data)


# =============================================================================
# ── QUEUE LENGTH PLOTTING ─────────────────────────────────────────────────────
# =============================================================================

def plot_queue_timeseries(df_queue, strategy, seed, out_dir):
    """
    Plot queue length over time for all intersections.
    Creates a grid of subplots, one per intersection.
    """
    if df_queue.empty:
        return
    
    intersections = sorted(df_queue['intersection_id'].unique())
    n_inter = len(intersections)
    
    if n_inter == 0:
        return
    
    # Create subplot grid (max 4 columns)
    ncols = min(4, n_inter)
    nrows = (n_inter + ncols - 1) // ncols
    
    fig, axes = plt.subplots(nrows, ncols, figsize=(5 * ncols, 3.5 * nrows))
    axes = axes.flatten() if n_inter > 1 else [axes]
    
    for idx, jct_id in enumerate(intersections):
        ax = axes[idx]
        jct_data = df_queue[df_queue['intersection_id'] == jct_id]
        
        if jct_data.empty:
            ax.set_visible(False)
            continue
        
        # Plot queue length over time
        times = jct_data['time'].values
        queues = jct_data['queue_length'].values
        
        ax.plot(times, queues, color=STRATEGY_COLOURS.get(strategy, DEFAULT_COLOUR),
                linewidth=1.5, label=f'{strategy} (seed {seed})')
        
        # Add 60-second interval markers
        for t in range(0, int(times.max()) + 1, INTERVAL_S):
            ax.axvline(x=t, color='gray', linestyle='--', alpha=0.3, linewidth=0.5)
        
        ax.set_title(f'Jct {jct_id}', fontsize=9, fontweight='bold')
        ax.set_xlabel('Time (s)', fontsize=8)
        ax.set_ylabel('Queue (veh)', fontsize=8)
        ax.legend(fontsize=7, loc='upper left')
        ax.grid(True, alpha=0.3)
        ax.set_axisbelow(True)
    
    # Hide unused subplots
    for idx in range(n_inter, len(axes)):
        axes[idx].set_visible(False)
    
    fig.suptitle(f'Queue Length Monitor — {strategy} (Seed {seed})',
                 fontsize=12, fontweight='bold', y=1.02)
    plt.tight_layout()
    
    safe_name = f"{strategy}_seed{seed}".replace('/', '_')
    out_path = os.path.join(out_dir, f"queue_timeseries_{safe_name}.png")
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"[QUEUE] Saved: {out_path}")


def plot_queue_comparison(df_queue, out_dir):
    """
    Compare queue lengths across strategies at 60-second snapshots.
    Shows mean queue length at each snapshot time.
    """
    if df_queue.empty:
        return
    
    strategies = df_queue['_strategy'].unique()
    if len(strategies) == 0:
        return
    
    # Create time bins (60-second intervals)
    df_queue['time_bin'] = (df_queue['time'] // INTERVAL_S) * INTERVAL_S
    
    # Calculate mean queue per strategy per time bin
    fig, axes = plt.subplots(2, 1, figsize=(14, 10))
    
    # Top plot: Mean queue length over time
    ax1 = axes[0]
    for strategy in strategies:
        s_data = df_queue[df_queue['_strategy'] == strategy]
        if s_data.empty:
            continue
        
        mean_queue = s_data.groupby('time_bin')['queue_length'].mean()
        std_queue = s_data.groupby('time_bin')['queue_length'].std().fillna(0)
        
        times = mean_queue.index
        means = mean_queue.values
        stds = std_queue.values
        
        color = STRATEGY_COLOURS.get(strategy, DEFAULT_COLOUR)
        ax1.plot(times, means, color=color, linewidth=2, label=strategy)
        ax1.fill_between(times, means - stds, means + stds,
                        alpha=0.2, color=color)
    
    ax1.set_title('Mean Queue Length Over Time (All Intersections)',
                   fontsize=12, fontweight='bold')
    ax1.set_xlabel('Time (s)', fontsize=10)
    ax1.set_ylabel('Mean Queue Length (veh)', fontsize=10)
    ax1.legend(fontsize=9)
    ax1.grid(True, alpha=0.3)
    ax1.set_axisbelow(True)
    
    # Bottom plot: Queue length distribution at key snapshots
    ax2 = axes[1]
    snapshot_times = [0, 900, 1800, 2700, 3600]  # Every 15 minutes
    snapshot_times = [t for t in snapshot_times if t <= df_queue['time_bin'].max()]
    
    x = np.arange(len(snapshot_times))
    width = 0.8 / len(strategies)
    
    for si, strategy in enumerate(strategies):
        s_data = df_queue[df_queue['_strategy'] == strategy]
        if s_data.empty:
            continue
        
        means_at_snapshots = []
        for t in snapshot_times:
            bin_data = s_data[s_data['time_bin'] == t]
            mean_q = bin_data['queue_length'].mean() if not bin_data.empty else 0
            means_at_snapshots.append(mean_q)
        
        offset = (si - len(strategies) / 2.0 + 0.5) * width
        color = STRATEGY_COLOURS.get(strategy, DEFAULT_COLOUR)
        ax2.bar(x + offset, means_at_snapshots, width, label=strategy,
               color=color, edgecolor='white', linewidth=0.5)
    
    ax2.set_title(f'Queue Length at {INTERVAL_S}-Second Snapshots',
                   fontsize=12, fontweight='bold')
    ax2.set_xlabel('Snapshot Time (s)', fontsize=10)
    ax2.set_ylabel('Mean Queue Length (veh)', fontsize=10)
    ax2.set_xticks(x)
    ax2.set_xticklabels([f'{t}s' for t in snapshot_times], fontsize=9)
    ax2.legend(fontsize=9)
    ax2.grid(True, alpha=0.3, axis='y')
    ax2.set_axisbelow(True)
    
    plt.tight_layout()
    out_path = os.path.join(out_dir, "queue_comparison_all_strategies.png")
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"[QUEUE] Saved: {out_path}")


def plot_queue_heatmap(df_queue, out_dir):
    """
    Create a heatmap of queue lengths: time (rows) × intersection (columns).
    """
    if df_queue.empty:
        return
    
    # Pivot table: time_bin as rows, intersection_id as columns
    pivot = df_queue.pivot_table(
        index='time_bin',
        columns='intersection_id',
        values='queue_length',
        aggfunc='mean'
    )
    
    if pivot.empty:
        return
    
    # Plot heatmap
    fig, ax = plt.subplots(figsize=(12, 8))
    
    im = ax.imshow(pivot.values, aspect='auto', cmap='YlOrRd', interpolation='nearest')
    
    # Set labels
    ax.set_xticks(range(len(pivot.columns)))
    ax.set_xticklabels(pivot.columns, rotation=45, ha='right', fontsize=8)
    ax.set_yticks(range(len(pivot.index)))
    ax.set_yticklabels([f'{int(t)}s' for t in pivot.index], fontsize=8)
    
    # Colorbar
    cbar = plt.colorbar(im, ax=ax)
    cbar.set_label('Mean Queue Length (veh)', fontsize=10)
    
    ax.set_title('Queue Length Heatmap (Time × Intersection)',
                 fontsize=12, fontweight='bold')
    ax.set_xlabel('Intersection ID', fontsize=10)
    ax.set_ylabel('Time', fontsize=10)
    
    plt.tight_layout()
    out_path = os.path.join(out_dir, "queue_heatmap.png")
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"[QUEUE] Saved: {out_path}")


# =============================================================================
# ── BUS TRACKING VERIFICATION ─────────────────────────────────────────────────
# =============================================================================

def verify_bus_tracking(results_root):
    """
    Verify that bus tracking is working correctly by checking:
    1. Bus detection events are recorded
    2. Bus positions are tracked over time
    3. TSP actions (extensions/insertions) are logged
    """
    print("\n" + "=" * 80)
    print("BUS TRACKING VERIFICATION")
    print("=" * 80)
    
    bus_tracking_ok = True
    issues = []
    
    for folder in os.listdir(results_root):
        fp = os.path.join(results_root, folder)
        if not os.path.isdir(fp):
            continue
        
        strategy, seed = _parse_folder(folder)
        if strategy is None:
            continue
        
        # Check for bus detection files
        detection_files = glob.glob(os.path.join(fp, "*detection*.csv"))
        if not detection_files:
            issues.append(f"  {folder}: No bus detection files found")
            bus_tracking_ok = False
            continue
        
        # Check for TSP action logs
        tsp_files = glob.glob(os.path.join(fp, "*tsp*.csv"))
        if not tsp_files and strategy not in ["NORMAL"]:
            issues.append(f"  {folder}: No TSP action logs found")
            bus_tracking_ok = False
        
        # Check detection file contents
        for df in detection_files:
            try:
                df_data = pd.read_csv(df)
                if df_data.empty:
                    issues.append(f"  {folder}: Empty detection file: {os.path.basename(df)}")
                    bus_tracking_ok = False
                else:
                    # Check for required columns
                    required = ['bus_id', 'timestamp', 'intersection_id']
                    missing = [col for col in required if col not in df_data.columns]
                    if missing:
                        issues.append(f"  {folder}: Missing columns {missing} in detection file")
                        bus_tracking_ok = False
            except Exception as e:
                issues.append(f"  {folder}: Error reading {os.path.basename(df)}: {e}")
                bus_tracking_ok = False
    
    if bus_tracking_ok:
        print("✓ Bus tracking appears to be working correctly")
    else:
        print("✗ Bus tracking issues detected:")
        for issue in issues:
            print(issue)
    
    return bus_tracking_ok, issues


# =============================================================================
# ── MAIN ──────────────────────────────────────────────────────────────────────
# =============================================================================

def main():
    print(f"[QUEUE] Queue Length Monitor")
    print(f"[QUEUE] Loading data from: {RESULTS_ROOT}")
    print(f"[QUEUE] Snapshot interval: {INTERVAL_S} seconds")
    
    os.makedirs(PLOTS_OUT, exist_ok=True)
    
    # Load section counts data
    df_section = load_section_counts(RESULTS_ROOT)
    if df_section.empty:
        print("[QUEUE] No section count data found. Queue plots will be limited.")
        print("[QUEUE] Ensure Simulation_Stats.py is generating section_counts_*.csv files.")
    else:
        print(f"[QUEUE] Loaded {len(df_section)} section count records")
    
    # Estimate queue lengths from detector data
    df_queue = estimate_queue_from_detectors(df_section)
    if df_queue.empty:
        print("[QUEUE] Could not estimate queues from detector data.")
        print("[QUEUE] Trying to load from existing queue files...")
        
        # Try loading pre-computed queue data
        queue_files = glob.glob(os.path.join(RESULTS_ROOT, "**/queue_*.csv"), recursive=True)
        if queue_files:
            all_queue = []
            for qf in queue_files:
                try:
                    df = pd.read_csv(qf)
                    strategy, seed = _parse_folder(os.path.dirname(qf).split(os.sep)[-1])
                    if strategy:
                        df['_strategy'] = strategy
                        df['_seed'] = seed
                        all_queue.append(df)
                except:
                    pass
            df_queue = pd.concat(all_queue, ignore_index=True) if all_queue else pd.DataFrame()

        if df_queue.empty:
            snapshot_files = glob.glob(os.path.join(RESULTS_ROOT, "**/queue_snapshot_*.csv"), recursive=True)
            if snapshot_files:
                print(f"[QUEUE] Found {len(snapshot_files)} queue snapshot file(s); plotting them directly.")
                for qf in sorted(snapshot_files):
                    _run_from_snapshot(qf)
                return
    
    if not df_queue.empty:
        print(f"[QUEUE] Queue data available for {len(df_queue['_strategy'].unique())} strategies")
        
        # Plot individual strategy timeseries
        for strategy in df_queue['_strategy'].unique():
            s_data = df_queue[df_queue['_strategy'] == strategy]
            for seed in s_data['_seed'].unique():
                seed_data = s_data[s_data['_seed'] == seed]
                plot_queue_timeseries(seed_data, strategy, seed, PLOTS_OUT)
        
        # Plot comparison across strategies
        plot_queue_comparison(df_queue, PLOTS_OUT)
        
        # Plot heatmap
        plot_queue_heatmap(df_queue, PLOTS_OUT)
    else:
        print("[QUEUE] No queue data available for plotting.")
    
    # Verify bus tracking
    bus_ok, bus_issues = verify_bus_tracking(RESULTS_ROOT)
    
    print(f"\n[QUEUE] All plots saved to: {PLOTS_OUT}")
    print("=" * 80)


def _run_from_snapshot(queue_csv: str) -> None:
    """Load a queue_snapshot_*.csv and produce queue plots directly.

    This bypasses the section_counts_*.csv / Aimsun-results workflow used by
    main() so the monitor works when called from AAPIFinish during a live run.
    """
    out_dir = os.path.join(os.path.dirname(queue_csv), "queue_monitor")
    os.makedirs(out_dir, exist_ok=True)

    try:
        df = pd.read_csv(queue_csv)
    except Exception as e:
        print(f"[QUEUE] Could not load {queue_csv}: {e}")
        return

    required = {'sim_time_s', 'junction_id', 'queue_main', 'queue_side'}
    if not required.issubset(df.columns):
        print(f"[QUEUE] Snapshot CSV missing columns. Available: {list(df.columns)}")
        return

    for col in ('sim_time_s', 'junction_id', 'queue_main', 'queue_side', 'queue_total',
                'queue_main_nb', 'queue_main_sb', 'queue_side_eb', 'queue_side_wb',
                'queue_slow_main', 'queue_slow_side'):
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

    junctions = sorted(df['junction_id'].unique())
    n = len(junctions)
    if n == 0:
        print("[QUEUE] No junction data in snapshot CSV.")
        return

    print(f"[QUEUE] Plotting {n} junctions from {os.path.basename(queue_csv)}")

    ncols = min(4, n)
    nrows = (n + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(5 * ncols, 3.5 * nrows),
                             squeeze=False)
    axes_flat = [axes[r][c] for r in range(nrows) for c in range(ncols)]

    # Check if directional queue data is available
    has_directional = all(col in df.columns for col in ['queue_main_nb', 'queue_main_sb', 'queue_side_eb', 'queue_side_wb'])

    for idx, jct_id in enumerate(junctions):
        ax = axes_flat[idx]
        jd = df[df['junction_id'] == jct_id].sort_values('sim_time_s')

        if has_directional:
            # Plot directional queues with clear legend
            ax.plot(jd['sim_time_s'], jd['queue_main_nb'],
                    color='steelblue', linewidth=1.5, label='Main NB')
            ax.plot(jd['sim_time_s'], jd['queue_main_sb'],
                    color='navy', linewidth=1.5, label='Main SB')
            ax.plot(jd['sim_time_s'], jd['queue_side_eb'],
                    color='coral', linewidth=1.5, label='Cross EB')
            ax.plot(jd['sim_time_s'], jd['queue_side_wb'],
                    color='darkred', linewidth=1.5, label='Cross WB')
        else:
            # Fall back to aggregated queues
            ax.plot(jd['sim_time_s'], jd['queue_main'],
                    color='steelblue', linewidth=1.5, label='Main')
            ax.plot(jd['sim_time_s'], jd['queue_side'],
                    color='coral', linewidth=1.5, label='Side')

        if 'queue_slow_main' in df.columns:
            ax.plot(jd['sim_time_s'], jd['queue_slow_main'],
                    color='navy', linewidth=1.0, linestyle='--', label='Slow-main')
        ax.set_title(f'Jct {int(jct_id)}', fontsize=9, fontweight='bold')
        ax.set_xlabel('Time (s)', fontsize=8)
        ax.set_ylabel('Queue (veh)', fontsize=8)
        ax.legend(fontsize=6, loc='upper left')
        ax.grid(True, alpha=0.3)

    for idx in range(n, len(axes_flat)):
        axes_flat[idx].set_visible(False)

    exp_name = os.path.basename(queue_csv).replace('queue_snapshot_', '').rsplit('_', 2)[0]
    fig.suptitle(f'Queue Monitor — {exp_name}', fontsize=12, fontweight='bold', y=1.01)
    plt.tight_layout()
    out_path = os.path.join(out_dir, f"queue_timeseries_{exp_name}.png")
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"[QUEUE] Saved: {out_path}")

    # Heatmap: time × junction
    try:
        pivot = df.pivot_table(index='sim_time_s', columns='junction_id',
                               values='queue_main', aggfunc='mean')
        if not pivot.empty:
            fig2, ax2 = plt.subplots(figsize=(max(8, n * 0.8), 6))
            im = ax2.imshow(pivot.values, aspect='auto', cmap='YlOrRd',
                            interpolation='nearest', origin='lower')
            ax2.set_xticks(range(len(pivot.columns)))
            ax2.set_xticklabels([str(int(c)) for c in pivot.columns],
                                rotation=45, ha='right', fontsize=7)
            ax2.set_yticks(range(0, len(pivot.index), max(1, len(pivot.index) // 10)))
            ax2.set_yticklabels(
                [f'{int(pivot.index[i])}s'
                 for i in range(0, len(pivot.index), max(1, len(pivot.index) // 10))],
                fontsize=7)
            plt.colorbar(im, ax=ax2, label='Main queue (veh)')
            ax2.set_title(f'Queue Heatmap — {exp_name}')
            ax2.set_xlabel('Junction ID')
            ax2.set_ylabel('Time (s)')
            plt.tight_layout()
            hm_path = os.path.join(out_dir, f"queue_heatmap_{exp_name}.png")
            plt.savefig(hm_path, dpi=150, bbox_inches='tight')
            plt.close(fig2)
            print(f"[QUEUE] Saved: {hm_path}")
    except Exception as _he:
        print(f"[QUEUE] Heatmap skipped: {_he}")

    print(f"[QUEUE] All plots saved to: {out_dir}")


def run(queue_csv=None, junc_csv=None):
    """Entry point called from AAPIFinish in intersection_controller.py."""
    if queue_csv and os.path.isfile(queue_csv):
        _run_from_snapshot(queue_csv)
        return
    main()


if __name__ == "__main__":
    main()